% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
% y = implementR2_opt(u)
%
% y: filtered output(s)
% u: intput(s)
%
% date: 16-Nov-2007 16:22:27
% Automatically generated by implementMATLAB / FWRToolbox


function y = implementR2_opt(u)

% initialize                   
u = round(2^11*u);y = zeros( length(u), 1 );xn = zeros(4,1);                
                               
for i=1:length(u)

    % intermediate variables    Acc0 = xn(1);    T0    = Acc0;    Acc1 = xn(2);    T1    = Acc1;    Acc2 = xn(3);    T2    = Acc2;    Acc3 = xn(4);    T3    = Acc3;    % states    Acc4 = T0    * -17601;    Acc4 = Acc4 + (T1) * 2^13;    Acc4 = Acc4 + xn(1) * 16342;    Acc4 = Acc4 + u(i)  * 4781;    xn(1) = floor( Acc4/2^14 );    Acc5 = T0    * -18065;    Acc5 = Acc5 + (T2) * 2^13;    Acc5 = Acc5 + xn(2) * 6775;    Acc5 = Acc5 + u(i)  * -2582;    xn(2) = floor( Acc5/2^14 );    Acc6 = T0    * -25826;    Acc6 = Acc6 + (T3) * 2^12;    Acc6 = Acc6 + xn(3) * 16162;    Acc6 = Acc6 + u(i)  * 944;    xn(3) = floor( Acc6/2^14 );    Acc7 = T0    * -30395;    Acc7 = Acc7 + xn(4) * 32554;    Acc7 = Acc7 + u(i)  * 1061;    xn(4) = floor( Acc7/2^15 );    % output(s)    Acc8 = T0;    y(i)  = Acc8;
    
end

y = 2^--6*y;