--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity inv_15 is
  port(
      i    : IN std_logic_vector( 14 downto 0);
      nq    : OUT std_logic_vector( 14 downto 0)
  );
end inv_15;



architecture behavioural of inv_15 is

component inv_x1
  port (
  i	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
);
end component;


begin
  inv_x1_i0 : inv_x1
  port map(
       i => i(0),
       nq => nq(0)
  );
  inv_x1_i1 : inv_x1
  port map(
       i => i(1),
       nq => nq(1)
  );
  inv_x1_i2 : inv_x1
  port map(
       i => i(2),
       nq => nq(2)
  );
  inv_x1_i3 : inv_x1
  port map(
       i => i(3),
       nq => nq(3)
  );
  inv_x1_i4 : inv_x1
  port map(
       i => i(4),
       nq => nq(4)
  );
  inv_x1_i5 : inv_x1
  port map(
       i => i(5),
       nq => nq(5)
  );
  inv_x1_i6 : inv_x1
  port map(
       i => i(6),
       nq => nq(6)
  );
  inv_x1_i7 : inv_x1
  port map(
       i => i(7),
       nq => nq(7)
  );
  inv_x1_i8 : inv_x1
  port map(
       i => i(8),
       nq => nq(8)
  );
  inv_x1_i9 : inv_x1
  port map(
       i => i(9),
       nq => nq(9)
  );
  inv_x1_i10 : inv_x1
  port map(
       i => i(10),
       nq => nq(10)
  );
  inv_x1_i11 : inv_x1
  port map(
       i => i(11),
       nq => nq(11)
  );
  inv_x1_i12 : inv_x1
  port map(
       i => i(12),
       nq => nq(12)
  );
  inv_x1_i13 : inv_x1
  port map(
       i => i(13),
       nq => nq(13)
  );
  inv_x1_i14 : inv_x1
  port map(
       i => i(14),
       nq => nq(14)
  );
end behavioural ;
