--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity a2_1 is
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end a2_1;



architecture behavioural of a2_1 is

component a2_x2
  port (
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
);
end component;


begin
  a2_x2_i0 : a2_x2
  port map(
       i1 => i1,
       i0 => i0,
       q => q
  );
end behavioural ;
