--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity constant_0b0100000000000000 is
  port(
      o    : OUT std_logic_vector( 15 downto 0)
  );
end constant_0b0100000000000000;



architecture behavioural of constant_0b0100000000000000 is

component zero_1
  port(
      nq    : OUT std_logic
  );
end component;


component one_1
  port(
      q    : OUT std_logic
  );
end component;


signal zero_s0 : std_logic;
signal zero_s1 : std_logic;
signal zero_s2 : std_logic;
signal zero_s3 : std_logic;
signal zero_s4 : std_logic;
signal zero_s5 : std_logic;
signal zero_s6 : std_logic;
signal zero_s7 : std_logic;
signal zero_s8 : std_logic;
signal zero_s9 : std_logic;
signal zero_s10 : std_logic;
signal zero_s11 : std_logic;
signal zero_s12 : std_logic;
signal zero_s13 : std_logic;
signal one_s14 : std_logic;
signal zero_s15 : std_logic;
begin
  zero_1_i0 : zero_1
  port map(
       nq => zero_s0
  );
  o(0) <= zero_s0;
  zero_1_i1 : zero_1
  port map(
       nq => zero_s1
  );
  o(1) <= zero_s1;
  zero_1_i2 : zero_1
  port map(
       nq => zero_s2
  );
  o(2) <= zero_s2;
  zero_1_i3 : zero_1
  port map(
       nq => zero_s3
  );
  o(3) <= zero_s3;
  zero_1_i4 : zero_1
  port map(
       nq => zero_s4
  );
  o(4) <= zero_s4;
  zero_1_i5 : zero_1
  port map(
       nq => zero_s5
  );
  o(5) <= zero_s5;
  zero_1_i6 : zero_1
  port map(
       nq => zero_s6
  );
  o(6) <= zero_s6;
  zero_1_i7 : zero_1
  port map(
       nq => zero_s7
  );
  o(7) <= zero_s7;
  zero_1_i8 : zero_1
  port map(
       nq => zero_s8
  );
  o(8) <= zero_s8;
  zero_1_i9 : zero_1
  port map(
       nq => zero_s9
  );
  o(9) <= zero_s9;
  zero_1_i10 : zero_1
  port map(
       nq => zero_s10
  );
  o(10) <= zero_s10;
  zero_1_i11 : zero_1
  port map(
       nq => zero_s11
  );
  o(11) <= zero_s11;
  zero_1_i12 : zero_1
  port map(
       nq => zero_s12
  );
  o(12) <= zero_s12;
  zero_1_i13 : zero_1
  port map(
       nq => zero_s13
  );
  o(13) <= zero_s13;
  one_1_i14 : one_1
  port map(
       q => one_s14
  );
  o(14) <= one_s14;
  zero_1_i15 : zero_1
  port map(
       nq => zero_s15
  );
  o(15) <= zero_s15;
end behavioural ;
