--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity full_adder is
  port(
      a    : IN std_logic;
      b    : IN std_logic;
      cin    : IN std_logic;
      sout    : OUT std_logic;
      cout    : OUT std_logic
  );
end full_adder;



architecture behavioural of full_adder is

component fulladder_x2
  port (
  a1	: IN STD_LOGIC;
  a2	: IN STD_LOGIC;
  a3	: IN STD_LOGIC;
  a4	: IN STD_LOGIC;
  b1	: IN STD_LOGIC;
  b2	: IN STD_LOGIC;
  b3	: IN STD_LOGIC;
  b4	: IN STD_LOGIC;
  cin1	: IN STD_LOGIC;
  cin2	: IN STD_LOGIC;
  cin3	: IN STD_LOGIC;
  cout	: OUT STD_LOGIC;
  sout	: OUT STD_LOGIC
);
end component;


begin
  fulladder_x2_i0 : fulladder_x2
  port map(
       b4 => b,
       b2 => b,
       sout => sout,
       cout => cout,
       a1 => a,
       a3 => a,
       a2 => a,
       b1 => b,
       b3 => b,
       cin1 => cin,
       cin2 => cin,
       cin3 => cin,
       a4 => a
  );
end behavioural ;
