--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity pg is
  port(
      p1    : IN std_logic;
      g1    : IN std_logic;
      p2    : IN std_logic;
      g2    : IN std_logic;
      p    : OUT std_logic;
      g    : OUT std_logic
  );
end pg;



architecture behavioural of pg is

component a2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


component o2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


signal bool_o0 : std_logic;
signal bool_o1 : std_logic;
signal bool_o2 : std_logic;
begin
  a2_1_i0 : a2_1
  port map(
       i1 => p2,
       i0 => p1,
       q => bool_o0
  );
  p <= bool_o0;
  a2_1_i1 : a2_1
  port map(
       i1 => p1,
       i0 => g2,
       q => bool_o1
  );
  o2_1_i2 : o2_1
  port map(
       i1 => bool_o1,
       i0 => g1,
       q => bool_o2
  );
  g <= bool_o2;
end behavioural ;
