--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity buf_15 is
  port(
      i    : IN std_logic_vector( 14 downto 0);
      q    : OUT std_logic_vector( 14 downto 0)
  );
end buf_15;



architecture behavioural of buf_15 is

component buf_x2
  port (
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
);
end component;


begin
  buf_x2_i0 : buf_x2
  port map(
       i => i(0),
       q => q(0)
  );
  buf_x2_i1 : buf_x2
  port map(
       i => i(1),
       q => q(1)
  );
  buf_x2_i2 : buf_x2
  port map(
       i => i(2),
       q => q(2)
  );
  buf_x2_i3 : buf_x2
  port map(
       i => i(3),
       q => q(3)
  );
  buf_x2_i4 : buf_x2
  port map(
       i => i(4),
       q => q(4)
  );
  buf_x2_i5 : buf_x2
  port map(
       i => i(5),
       q => q(5)
  );
  buf_x2_i6 : buf_x2
  port map(
       i => i(6),
       q => q(6)
  );
  buf_x2_i7 : buf_x2
  port map(
       i => i(7),
       q => q(7)
  );
  buf_x2_i8 : buf_x2
  port map(
       i => i(8),
       q => q(8)
  );
  buf_x2_i9 : buf_x2
  port map(
       i => i(9),
       q => q(9)
  );
  buf_x2_i10 : buf_x2
  port map(
       i => i(10),
       q => q(10)
  );
  buf_x2_i11 : buf_x2
  port map(
       i => i(11),
       q => q(11)
  );
  buf_x2_i12 : buf_x2
  port map(
       i => i(12),
       q => q(12)
  );
  buf_x2_i13 : buf_x2
  port map(
       i => i(13),
       q => q(13)
  );
  buf_x2_i14 : buf_x2
  port map(
       i => i(14),
       q => q(14)
  );
end behavioural ;
