--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity dadda_17eb5ba4c1d3cec141be4c2e5190d20c is
  port(
      pp3    : IN std_logic;
      pp2    : IN std_logic_vector( 15 downto 0);
      pp1    : IN std_logic;
      pp0    : IN std_logic_vector( 15 downto 0);
      pp7    : IN std_logic_vector( 15 downto 0);
      pp6    : IN std_logic;
      pp5    : IN std_logic_vector( 15 downto 0);
      pp4    : IN std_logic_vector( 15 downto 0);
      pp8    : IN std_logic;
      fadcst    : IN std_logic_vector( 15 downto 0);
      s0    : OUT std_logic_vector( 31 downto 0);
      s1    : OUT std_logic_vector( 31 downto 0)
  );
end dadda_17eb5ba4c1d3cec141be4c2e5190d20c;



architecture behavioural of dadda_17eb5ba4c1d3cec141be4c2e5190d20c is

component ha
  port(
      a    : IN std_logic;
      b    : IN std_logic;
      sout    : OUT std_logic;
      cout    : OUT std_logic
  );
end component;


component fa
  port(
      a    : IN std_logic;
      b    : IN std_logic;
      cin    : IN std_logic;
      sout    : OUT std_logic;
      cout    : OUT std_logic
  );
end component;


component zero_1
  port(
      nq    : OUT std_logic
  );
end component;


component buf_1
  port(
      i    : IN std_logic;
      q    : OUT std_logic
  );
end component;


signal sout_ha1 : std_logic;
signal cout_ha1 : std_logic;
signal sout_ha2 : std_logic;
signal cout_ha2 : std_logic;
signal sout_fa1 : std_logic;
signal cout_fa1 : std_logic;
signal sout_ha3 : std_logic;
signal cout_ha3 : std_logic;
signal sout_fa2 : std_logic;
signal cout_fa2 : std_logic;
signal sout_ha4 : std_logic;
signal cout_ha4 : std_logic;
signal sout_fa3 : std_logic;
signal cout_fa3 : std_logic;
signal sout_fa4 : std_logic;
signal cout_fa4 : std_logic;
signal sout_fa5 : std_logic;
signal cout_fa5 : std_logic;
signal sout_ha5 : std_logic;
signal cout_ha5 : std_logic;
signal sout_fa6 : std_logic;
signal cout_fa6 : std_logic;
signal sout_ha6 : std_logic;
signal cout_ha6 : std_logic;
signal sout_fa7 : std_logic;
signal cout_fa7 : std_logic;
signal sout_ha7 : std_logic;
signal cout_ha7 : std_logic;
signal sout_fa8 : std_logic;
signal cout_fa8 : std_logic;
signal sout_ha8 : std_logic;
signal cout_ha8 : std_logic;
signal sout_ha9 : std_logic;
signal cout_ha9 : std_logic;
signal sout_ha10 : std_logic;
signal cout_ha10 : std_logic;
signal sout_fa9 : std_logic;
signal cout_fa9 : std_logic;
signal sout_fa10 : std_logic;
signal cout_fa10 : std_logic;
signal sout_fa11 : std_logic;
signal cout_fa11 : std_logic;
signal sout_fa12 : std_logic;
signal cout_fa12 : std_logic;
signal sout_fa13 : std_logic;
signal cout_fa13 : std_logic;
signal sout_fa14 : std_logic;
signal cout_fa14 : std_logic;
signal sout_fa15 : std_logic;
signal cout_fa15 : std_logic;
signal sout_fa16 : std_logic;
signal cout_fa16 : std_logic;
signal sout_fa17 : std_logic;
signal cout_fa17 : std_logic;
signal sout_fa18 : std_logic;
signal cout_fa18 : std_logic;
signal sout_fa19 : std_logic;
signal cout_fa19 : std_logic;
signal sout_ha11 : std_logic;
signal cout_ha11 : std_logic;
signal sout_ha12 : std_logic;
signal cout_ha12 : std_logic;
signal sout_ha13 : std_logic;
signal cout_ha13 : std_logic;
signal sout_ha14 : std_logic;
signal cout_ha14 : std_logic;
signal sout_ha15 : std_logic;
signal cout_ha15 : std_logic;
signal sout_ha16 : std_logic;
signal cout_ha16 : std_logic;
signal sout_ha17 : std_logic;
signal cout_ha17 : std_logic;
signal sout_fa20 : std_logic;
signal cout_fa20 : std_logic;
signal sout_fa21 : std_logic;
signal cout_fa21 : std_logic;
signal sout_fa22 : std_logic;
signal cout_fa22 : std_logic;
signal sout_fa23 : std_logic;
signal cout_fa23 : std_logic;
signal sout_fa24 : std_logic;
signal cout_fa24 : std_logic;
signal sout_fa25 : std_logic;
signal cout_fa25 : std_logic;
signal sout_fa26 : std_logic;
signal cout_fa26 : std_logic;
signal sout_fa27 : std_logic;
signal cout_fa27 : std_logic;
signal sout_fa28 : std_logic;
signal cout_fa28 : std_logic;
signal sout_fa29 : std_logic;
signal cout_fa29 : std_logic;
signal sout_fa30 : std_logic;
signal cout_fa30 : std_logic;
signal sout_fa31 : std_logic;
signal cout_fa31 : std_logic;
signal sout_fa32 : std_logic;
signal cout_fa32 : std_logic;
signal sout_fa33 : std_logic;
signal cout_fa33 : std_logic;
signal sout_fa34 : std_logic;
signal cout_fa34 : std_logic;
signal sout_fa35 : std_logic;
signal cout_fa35 : std_logic;
signal sout_fa36 : std_logic;
signal cout_fa36 : std_logic;
signal sout_fa37 : std_logic;
signal cout_fa37 : std_logic;
signal sout_fa38 : std_logic;
signal cout_fa38 : std_logic;
signal sout_fa39 : std_logic;
signal cout_fa39 : std_logic;
signal sout_fa40 : std_logic;
signal cout_fa40 : std_logic;
signal sout_fa41 : std_logic;
signal cout_fa41 : std_logic;
signal sout_ha18 : std_logic;
signal cout_ha18 : std_logic;
signal zero_s0 : std_logic;
signal zero_s1 : std_logic;
signal buf_o2 : std_logic;
signal buf_o3 : std_logic;
signal buf_o4 : std_logic;
signal zero_s5 : std_logic;
signal buf_o6 : std_logic;
signal zero_s7 : std_logic;
signal buf_o8 : std_logic;
signal buf_o9 : std_logic;
signal buf_o10 : std_logic;
signal zero_s11 : std_logic;
begin
  ha_i0 : ha
  port map(
       a => pp2(8),
       b => pp0(11),
       cout => cout_ha1,
       sout => sout_ha1
  );
  ha_i1 : ha
  port map(
       a => pp2(9),
       b => pp0(12),
       cout => cout_ha2,
       sout => sout_ha2
  );
  fa_i2 : fa
  port map(
       a => pp2(10),
       b => pp0(13),
       cout => cout_fa1,
       cin => pp7(0),
       sout => sout_fa1
  );
  ha_i3 : ha
  port map(
       a => pp5(2),
       b => pp4(7),
       cout => cout_ha3,
       sout => sout_ha3
  );
  fa_i4 : fa
  port map(
       a => pp2(11),
       b => pp0(14),
       cout => cout_fa2,
       cin => pp7(1),
       sout => sout_fa2
  );
  ha_i5 : ha
  port map(
       a => pp5(3),
       b => pp4(8),
       cout => cout_ha4,
       sout => sout_ha4
  );
  fa_i6 : fa
  port map(
       a => pp2(12),
       b => pp0(15),
       cout => cout_fa3,
       cin => pp7(2),
       sout => sout_fa3
  );
  fa_i7 : fa
  port map(
       a => pp5(4),
       b => pp4(9),
       cout => cout_fa4,
       cin => fadcst(0),
       sout => sout_fa4
  );
  fa_i8 : fa
  port map(
       a => pp2(13),
       b => pp7(3),
       cout => cout_fa5,
       cin => pp5(5),
       sout => sout_fa5
  );
  ha_i9 : ha
  port map(
       a => pp4(10),
       b => fadcst(1),
       cout => cout_ha5,
       sout => sout_ha5
  );
  fa_i10 : fa
  port map(
       a => pp2(14),
       b => pp7(4),
       cout => cout_fa6,
       cin => pp5(6),
       sout => sout_fa6
  );
  ha_i11 : ha
  port map(
       a => pp4(11),
       b => fadcst(2),
       cout => cout_ha6,
       sout => sout_ha6
  );
  fa_i12 : fa
  port map(
       a => pp2(15),
       b => pp7(5),
       cout => cout_fa7,
       cin => pp5(7),
       sout => sout_fa7
  );
  ha_i13 : ha
  port map(
       a => pp4(12),
       b => fadcst(3),
       cout => cout_ha7,
       sout => sout_ha7
  );
  fa_i14 : fa
  port map(
       a => pp7(6),
       b => pp5(8),
       cout => cout_fa8,
       cin => pp4(13),
       sout => sout_fa8
  );
  ha_i15 : ha
  port map(
       a => pp7(7),
       b => pp5(9),
       cout => cout_ha8,
       sout => sout_ha8
  );
  ha_i16 : ha
  port map(
       a => pp7(8),
       b => pp5(10),
       cout => cout_ha9,
       sout => sout_ha9
  );
  ha_i17 : ha
  port map(
       a => pp6,
       b => pp5(0),
       cout => cout_ha10,
       sout => sout_ha10
  );
  fa_i18 : fa
  port map(
       a => pp5(1),
       b => pp4(6),
       cout => cout_fa9,
       cin => cout_ha1,
       sout => sout_fa9
  );
  fa_i19 : fa
  port map(
       a => pp8,
       b => cout_ha2,
       cout => cout_fa10,
       cin => sout_fa1,
       sout => sout_fa10
  );
  fa_i20 : fa
  port map(
       a => cout_fa1,
       b => cout_ha3,
       cout => cout_fa11,
       cin => sout_fa2,
       sout => sout_fa11
  );
  fa_i21 : fa
  port map(
       a => cout_fa2,
       b => cout_ha4,
       cout => cout_fa12,
       cin => sout_fa3,
       sout => sout_fa12
  );
  fa_i22 : fa
  port map(
       a => cout_fa3,
       b => cout_fa4,
       cout => cout_fa13,
       cin => sout_fa5,
       sout => sout_fa13
  );
  fa_i23 : fa
  port map(
       a => cout_fa5,
       b => cout_ha5,
       cout => cout_fa14,
       cin => sout_fa6,
       sout => sout_fa14
  );
  fa_i24 : fa
  port map(
       a => cout_fa6,
       b => cout_ha6,
       cout => cout_fa15,
       cin => sout_fa7,
       sout => sout_fa15
  );
  fa_i25 : fa
  port map(
       a => fadcst(4),
       b => cout_fa7,
       cout => cout_fa16,
       cin => cout_ha7,
       sout => sout_fa16
  );
  fa_i26 : fa
  port map(
       a => pp4(14),
       b => fadcst(5),
       cout => cout_fa17,
       cin => cout_fa8,
       sout => sout_fa17
  );
  fa_i27 : fa
  port map(
       a => pp4(15),
       b => fadcst(6),
       cout => cout_fa18,
       cin => cout_ha8,
       sout => sout_fa18
  );
  fa_i28 : fa
  port map(
       a => pp7(9),
       b => pp5(11),
       cout => cout_fa19,
       cin => fadcst(7),
       sout => sout_fa19
  );
  ha_i29 : ha
  port map(
       a => pp7(10),
       b => pp5(12),
       cout => cout_ha11,
       sout => sout_ha11
  );
  ha_i30 : ha
  port map(
       a => pp7(11),
       b => pp5(13),
       cout => cout_ha12,
       sout => sout_ha12
  );
  ha_i31 : ha
  port map(
       a => pp7(12),
       b => pp5(14),
       cout => cout_ha13,
       sout => sout_ha13
  );
  ha_i32 : ha
  port map(
       a => pp7(13),
       b => pp5(15),
       cout => cout_ha14,
       sout => sout_ha14
  );
  ha_i33 : ha
  port map(
       a => pp3,
       b => pp2(0),
       cout => cout_ha15,
       sout => sout_ha15
  );
  s0(5) <= cout_ha15;
  s1(4) <= sout_ha15;
  ha_i34 : ha
  port map(
       a => pp2(1),
       b => pp0(4),
       cout => cout_ha16,
       sout => sout_ha16
  );
  s0(6) <= cout_ha16;
  s1(5) <= sout_ha16;
  ha_i35 : ha
  port map(
       a => pp2(2),
       b => pp0(5),
       cout => cout_ha17,
       sout => sout_ha17
  );
  s0(7) <= cout_ha17;
  s1(6) <= sout_ha17;
  fa_i36 : fa
  port map(
       a => pp2(3),
       b => pp0(6),
       cout => cout_fa20,
       cin => pp4(0),
       sout => sout_fa20
  );
  s0(8) <= cout_fa20;
  s1(7) <= sout_fa20;
  fa_i37 : fa
  port map(
       a => pp2(4),
       b => pp0(7),
       cout => cout_fa21,
       cin => pp4(1),
       sout => sout_fa21
  );
  s0(9) <= cout_fa21;
  s1(8) <= sout_fa21;
  fa_i38 : fa
  port map(
       a => pp2(5),
       b => pp0(8),
       cout => cout_fa22,
       cin => pp4(2),
       sout => sout_fa22
  );
  s0(10) <= cout_fa22;
  s1(9) <= sout_fa22;
  fa_i39 : fa
  port map(
       a => pp2(6),
       b => pp0(9),
       cout => cout_fa23,
       cin => pp4(3),
       sout => sout_fa23
  );
  s0(11) <= cout_fa23;
  s1(10) <= sout_fa23;
  fa_i40 : fa
  port map(
       a => pp2(7),
       b => pp0(10),
       cout => cout_fa24,
       cin => pp4(4),
       sout => sout_fa24
  );
  s0(12) <= cout_fa24;
  s1(11) <= sout_fa24;
  fa_i41 : fa
  port map(
       a => pp4(5),
       b => sout_ha1,
       cout => cout_fa25,
       cin => sout_ha10,
       sout => sout_fa25
  );
  s0(13) <= cout_fa25;
  s1(12) <= sout_fa25;
  fa_i42 : fa
  port map(
       a => sout_ha2,
       b => cout_ha10,
       cout => cout_fa26,
       cin => sout_fa9,
       sout => sout_fa26
  );
  s0(14) <= cout_fa26;
  s1(13) <= sout_fa26;
  fa_i43 : fa
  port map(
       a => sout_ha3,
       b => cout_fa9,
       cout => cout_fa27,
       cin => sout_fa10,
       sout => sout_fa27
  );
  s0(15) <= cout_fa27;
  s1(14) <= sout_fa27;
  fa_i44 : fa
  port map(
       a => sout_ha4,
       b => cout_fa10,
       cout => cout_fa28,
       cin => sout_fa11,
       sout => sout_fa28
  );
  s0(16) <= cout_fa28;
  s1(15) <= sout_fa28;
  fa_i45 : fa
  port map(
       a => sout_fa4,
       b => cout_fa11,
       cout => cout_fa29,
       cin => sout_fa12,
       sout => sout_fa29
  );
  s0(17) <= cout_fa29;
  s1(16) <= sout_fa29;
  fa_i46 : fa
  port map(
       a => sout_ha5,
       b => cout_fa12,
       cout => cout_fa30,
       cin => sout_fa13,
       sout => sout_fa30
  );
  s0(18) <= cout_fa30;
  s1(17) <= sout_fa30;
  fa_i47 : fa
  port map(
       a => sout_ha6,
       b => cout_fa13,
       cout => cout_fa31,
       cin => sout_fa14,
       sout => sout_fa31
  );
  s0(19) <= cout_fa31;
  s1(18) <= sout_fa31;
  fa_i48 : fa
  port map(
       a => sout_ha7,
       b => cout_fa14,
       cout => cout_fa32,
       cin => sout_fa15,
       sout => sout_fa32
  );
  s0(20) <= cout_fa32;
  s1(19) <= sout_fa32;
  fa_i49 : fa
  port map(
       a => sout_fa8,
       b => cout_fa15,
       cout => cout_fa33,
       cin => sout_fa16,
       sout => sout_fa33
  );
  s0(21) <= cout_fa33;
  s1(20) <= sout_fa33;
  fa_i50 : fa
  port map(
       a => sout_ha8,
       b => cout_fa16,
       cout => cout_fa34,
       cin => sout_fa17,
       sout => sout_fa34
  );
  s0(22) <= cout_fa34;
  s1(21) <= sout_fa34;
  fa_i51 : fa
  port map(
       a => sout_ha9,
       b => cout_fa17,
       cout => cout_fa35,
       cin => sout_fa18,
       sout => sout_fa35
  );
  s0(23) <= cout_fa35;
  s1(22) <= sout_fa35;
  fa_i52 : fa
  port map(
       a => cout_ha9,
       b => cout_fa18,
       cout => cout_fa36,
       cin => sout_fa19,
       sout => sout_fa36
  );
  s0(24) <= cout_fa36;
  s1(23) <= sout_fa36;
  fa_i53 : fa
  port map(
       a => fadcst(8),
       b => cout_fa19,
       cout => cout_fa37,
       cin => sout_ha11,
       sout => sout_fa37
  );
  s0(25) <= cout_fa37;
  s1(24) <= sout_fa37;
  fa_i54 : fa
  port map(
       a => fadcst(9),
       b => cout_ha11,
       cout => cout_fa38,
       cin => sout_ha12,
       sout => sout_fa38
  );
  s0(26) <= cout_fa38;
  s1(25) <= sout_fa38;
  fa_i55 : fa
  port map(
       a => fadcst(10),
       b => cout_ha12,
       cout => cout_fa39,
       cin => sout_ha13,
       sout => sout_fa39
  );
  s0(27) <= cout_fa39;
  s1(26) <= sout_fa39;
  fa_i56 : fa
  port map(
       a => fadcst(11),
       b => cout_ha13,
       cout => cout_fa40,
       cin => sout_ha14,
       sout => sout_fa40
  );
  s0(28) <= cout_fa40;
  s1(27) <= sout_fa40;
  fa_i57 : fa
  port map(
       a => pp7(14),
       b => fadcst(12),
       cout => cout_fa41,
       cin => cout_ha14,
       sout => sout_fa41
  );
  s0(29) <= cout_fa41;
  s1(28) <= sout_fa41;
  ha_i58 : ha
  port map(
       a => pp7(15),
       b => fadcst(13),
       cout => cout_ha18,
       sout => sout_ha18
  );
  s1(30) <= cout_ha18;
  s1(29) <= sout_ha18;
  zero_1_i59 : zero_1
  port map(
       nq => zero_s0
  );
  s0(0) <= zero_s0;
  zero_1_i60 : zero_1
  port map(
       nq => zero_s1
  );
  s1(0) <= zero_s1;
  buf_1_i61 : buf_1
  port map(
       q => buf_o2,
       i => pp1
  );
  s0(1) <= buf_o2;
  buf_1_i62 : buf_1
  port map(
       q => buf_o3,
       i => pp0(0)
  );
  s1(1) <= buf_o3;
  buf_1_i63 : buf_1
  port map(
       q => buf_o4,
       i => pp0(1)
  );
  s0(2) <= buf_o4;
  zero_1_i64 : zero_1
  port map(
       nq => zero_s5
  );
  s1(2) <= zero_s5;
  buf_1_i65 : buf_1
  port map(
       q => buf_o6,
       i => pp0(2)
  );
  s0(3) <= buf_o6;
  zero_1_i66 : zero_1
  port map(
       nq => zero_s7
  );
  s1(3) <= zero_s7;
  buf_1_i67 : buf_1
  port map(
       q => buf_o8,
       i => pp0(3)
  );
  s0(4) <= buf_o8;
  buf_1_i68 : buf_1
  port map(
       q => buf_o9,
       i => fadcst(14)
  );
  s0(30) <= buf_o9;
  buf_1_i69 : buf_1
  port map(
       q => buf_o10,
       i => fadcst(15)
  );
  s0(31) <= buf_o10;
  zero_1_i70 : zero_1
  port map(
       nq => zero_s11
  );
  s1(31) <= zero_s11;
end behavioural ;
