--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity mulc16_16 is
  port(
      a    : IN std_logic_vector( 15 downto 0);
      s    : OUT std_logic_vector( 31 downto 0)
  );
end mulc16_16;



architecture behavioural of mulc16_16 is

component ppmultcst_a16_cfm20370p9999617_sfad
  port(
      a    : IN std_logic_vector( 15 downto 0);
      pp0    : OUT std_logic_vector( 15 downto 0);
      pp1    : OUT std_logic;
      pp2    : OUT std_logic_vector( 15 downto 0);
      pp3    : OUT std_logic;
      pp4    : OUT std_logic_vector( 15 downto 0);
      pp5    : OUT std_logic_vector( 15 downto 0);
      pp6    : OUT std_logic;
      pp7    : OUT std_logic_vector( 15 downto 0);
      pp8    : OUT std_logic;
      fadcst    : OUT std_logic_vector( 15 downto 0)
  );
end component;


component dadda_17eb5ba4c1d3cec141be4c2e5190d20c
  port(
      pp3    : IN std_logic;
      pp2    : IN std_logic_vector( 15 downto 0);
      pp1    : IN std_logic;
      pp0    : IN std_logic_vector( 15 downto 0);
      pp7    : IN std_logic_vector( 15 downto 0);
      pp6    : IN std_logic;
      pp5    : IN std_logic_vector( 15 downto 0);
      pp4    : IN std_logic_vector( 15 downto 0);
      pp8    : IN std_logic;
      fadcst    : IN std_logic_vector( 15 downto 0);
      s0    : OUT std_logic_vector( 31 downto 0);
      s1    : OUT std_logic_vector( 31 downto 0)
  );
end component;


component slansky_i0i132
  port(
      i0    : IN std_logic_vector( 31 downto 0);
      i1    : IN std_logic_vector( 31 downto 0);
      o    : OUT std_logic_vector( 31 downto 0)
  );
end component;


signal pp8 : std_logic;
signal fadcst : std_logic_vector( 15 downto 0);
signal pp3 : std_logic;
signal pp2 : std_logic_vector( 15 downto 0);
signal pp1 : std_logic;
signal pp0 : std_logic_vector( 15 downto 0);
signal pp7 : std_logic_vector( 15 downto 0);
signal pp6 : std_logic;
signal pp5 : std_logic_vector( 15 downto 0);
signal pp4 : std_logic_vector( 15 downto 0);
signal s0 : std_logic_vector( 31 downto 0);
signal s1 : std_logic_vector( 31 downto 0);
begin
  ppmultcst_a16_cfm20370p9999617_sfad_i0 : ppmultcst_a16_cfm20370p9999617_sfad
  port map(
       a => a,
       pp3 => pp3,
       pp2 => pp2,
       pp1 => pp1,
       pp0 => pp0,
       pp7 => pp7,
       pp6 => pp6,
       pp5 => pp5,
       pp4 => pp4,
       pp8 => pp8,
       fadcst => fadcst
  );
  dadda_17eb5ba4c1d3cec141be4c2e5190d20c_i1 : dadda_17eb5ba4c1d3cec141be4c2e5190d20c
  port map(
       s1 => s1,
       s0 => s0,
       pp3 => pp3,
       pp2 => pp2,
       pp1 => pp1,
       pp0 => pp0,
       pp7 => pp7,
       pp6 => pp6,
       pp5 => pp5,
       pp4 => pp4,
       pp8 => pp8,
       fadcst => fadcst
  );
  slansky_i0i132_i2 : slansky_i0i132
  port map(
       i1 => s1,
       i0 => s0,
       o => s
  );
end behavioural ;
