--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity pigi is
  port(
      a    : IN std_logic;
      b    : IN std_logic;
      pi    : OUT std_logic;
      gi    : OUT std_logic
  );
end pigi;



architecture behavioural of pigi is

component xr2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


component a2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


signal bool_o0 : std_logic;
signal bool_o1 : std_logic;
begin
  xr2_1_i0 : xr2_1
  port map(
       i1 => b,
       i0 => a,
       q => bool_o0
  );
  pi <= bool_o0;
  a2_1_i1 : a2_1
  port map(
       i1 => b,
       i0 => a,
       q => bool_o1
  );
  gi <= bool_o1;
end behavioural ;
