--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity ppmultcst_a16_cfm20370p9999617_sfad is
  port(
      a    : IN std_logic_vector( 15 downto 0);
      pp0    : OUT std_logic_vector( 15 downto 0);
      pp1    : OUT std_logic;
      pp2    : OUT std_logic_vector( 15 downto 0);
      pp3    : OUT std_logic;
      pp4    : OUT std_logic_vector( 15 downto 0);
      pp5    : OUT std_logic_vector( 15 downto 0);
      pp6    : OUT std_logic;
      pp7    : OUT std_logic_vector( 15 downto 0);
      pp8    : OUT std_logic;
      fadcst    : OUT std_logic_vector( 15 downto 0)
  );
end ppmultcst_a16_cfm20370p9999617_sfad;



architecture behavioural of ppmultcst_a16_cfm20370p9999617_sfad is

component inv_15
  port(
      i    : IN std_logic_vector( 14 downto 0);
      nq    : OUT std_logic_vector( 14 downto 0)
  );
end component;


component buf_1
  port(
      i    : IN std_logic;
      q    : OUT std_logic
  );
end component;


component one_1
  port(
      q    : OUT std_logic
  );
end component;


component buf_15
  port(
      i    : IN std_logic_vector( 14 downto 0);
      q    : OUT std_logic_vector( 14 downto 0)
  );
end component;


component inv_1
  port(
      i    : IN std_logic;
      nq    : OUT std_logic
  );
end component;


component constant_0b1101011110110111
  port(
      o    : OUT std_logic_vector( 15 downto 0)
  );
end component;


signal inv_o0 : std_logic_vector( 14 downto 0);
signal buf_o1 : std_logic;
signal one_s2 : std_logic;
signal inv_o3 : std_logic_vector( 14 downto 0);
signal buf_o4 : std_logic;
signal one_s5 : std_logic;
signal buf_o6 : std_logic_vector( 14 downto 0);
signal inv_o7 : std_logic;
signal inv_o8 : std_logic_vector( 14 downto 0);
signal buf_o9 : std_logic;
signal one_s10 : std_logic;
signal inv_o11 : std_logic_vector( 14 downto 0);
signal buf_o12 : std_logic;
signal one_s13 : std_logic;
signal cst_o14 : std_logic_vector( 15 downto 0);
begin
  inv_15_i0 : inv_15
  port map(
       i => a(14 downto 0),
       nq => inv_o0
  );
  pp0(0) <= inv_o0(0);
  pp0(1) <= inv_o0(1);
  pp0(2) <= inv_o0(2);
  pp0(3) <= inv_o0(3);
  pp0(4) <= inv_o0(4);
  pp0(5) <= inv_o0(5);
  pp0(6) <= inv_o0(6);
  pp0(7) <= inv_o0(7);
  pp0(8) <= inv_o0(8);
  pp0(9) <= inv_o0(9);
  pp0(10) <= inv_o0(10);
  pp0(11) <= inv_o0(11);
  pp0(12) <= inv_o0(12);
  pp0(13) <= inv_o0(13);
  pp0(14) <= inv_o0(14);
  buf_1_i1 : buf_1
  port map(
       q => buf_o1,
       i => a(15)
  );
  pp0(15) <= buf_o1;
  one_1_i2 : one_1
  port map(
       q => one_s2
  );
  pp1 <= one_s2;
  inv_15_i3 : inv_15
  port map(
       i => a(14 downto 0),
       nq => inv_o3
  );
  pp2(0) <= inv_o3(0);
  pp2(1) <= inv_o3(1);
  pp2(2) <= inv_o3(2);
  pp2(3) <= inv_o3(3);
  pp2(4) <= inv_o3(4);
  pp2(5) <= inv_o3(5);
  pp2(6) <= inv_o3(6);
  pp2(7) <= inv_o3(7);
  pp2(8) <= inv_o3(8);
  pp2(9) <= inv_o3(9);
  pp2(10) <= inv_o3(10);
  pp2(11) <= inv_o3(11);
  pp2(12) <= inv_o3(12);
  pp2(13) <= inv_o3(13);
  pp2(14) <= inv_o3(14);
  buf_1_i4 : buf_1
  port map(
       q => buf_o4,
       i => a(15)
  );
  pp2(15) <= buf_o4;
  one_1_i5 : one_1
  port map(
       q => one_s5
  );
  pp3 <= one_s5;
  buf_15_i6 : buf_15
  port map(
       q => buf_o6,
       i => a(14 downto 0)
  );
  pp4(0) <= buf_o6(0);
  pp4(1) <= buf_o6(1);
  pp4(2) <= buf_o6(2);
  pp4(3) <= buf_o6(3);
  pp4(4) <= buf_o6(4);
  pp4(5) <= buf_o6(5);
  pp4(6) <= buf_o6(6);
  pp4(7) <= buf_o6(7);
  pp4(8) <= buf_o6(8);
  pp4(9) <= buf_o6(9);
  pp4(10) <= buf_o6(10);
  pp4(11) <= buf_o6(11);
  pp4(12) <= buf_o6(12);
  pp4(13) <= buf_o6(13);
  pp4(14) <= buf_o6(14);
  inv_1_i7 : inv_1
  port map(
       i => a(15),
       nq => inv_o7
  );
  pp4(15) <= inv_o7;
  inv_15_i8 : inv_15
  port map(
       i => a(14 downto 0),
       nq => inv_o8
  );
  pp5(0) <= inv_o8(0);
  pp5(1) <= inv_o8(1);
  pp5(2) <= inv_o8(2);
  pp5(3) <= inv_o8(3);
  pp5(4) <= inv_o8(4);
  pp5(5) <= inv_o8(5);
  pp5(6) <= inv_o8(6);
  pp5(7) <= inv_o8(7);
  pp5(8) <= inv_o8(8);
  pp5(9) <= inv_o8(9);
  pp5(10) <= inv_o8(10);
  pp5(11) <= inv_o8(11);
  pp5(12) <= inv_o8(12);
  pp5(13) <= inv_o8(13);
  pp5(14) <= inv_o8(14);
  buf_1_i9 : buf_1
  port map(
       q => buf_o9,
       i => a(15)
  );
  pp5(15) <= buf_o9;
  one_1_i10 : one_1
  port map(
       q => one_s10
  );
  pp6 <= one_s10;
  inv_15_i11 : inv_15
  port map(
       i => a(14 downto 0),
       nq => inv_o11
  );
  pp7(0) <= inv_o11(0);
  pp7(1) <= inv_o11(1);
  pp7(2) <= inv_o11(2);
  pp7(3) <= inv_o11(3);
  pp7(4) <= inv_o11(4);
  pp7(5) <= inv_o11(5);
  pp7(6) <= inv_o11(6);
  pp7(7) <= inv_o11(7);
  pp7(8) <= inv_o11(8);
  pp7(9) <= inv_o11(9);
  pp7(10) <= inv_o11(10);
  pp7(11) <= inv_o11(11);
  pp7(12) <= inv_o11(12);
  pp7(13) <= inv_o11(13);
  pp7(14) <= inv_o11(14);
  buf_1_i12 : buf_1
  port map(
       q => buf_o12,
       i => a(15)
  );
  pp7(15) <= buf_o12;
  one_1_i13 : one_1
  port map(
       q => one_s13
  );
  pp8 <= one_s13;
  constant_0b1101011110110111_i14 : constant_0b1101011110110111
  port map(
       o => cst_o14
  );
  fadcst(0) <= cst_o14(0);
  fadcst(1) <= cst_o14(1);
  fadcst(2) <= cst_o14(2);
  fadcst(3) <= cst_o14(3);
  fadcst(4) <= cst_o14(4);
  fadcst(5) <= cst_o14(5);
  fadcst(6) <= cst_o14(6);
  fadcst(7) <= cst_o14(7);
  fadcst(8) <= cst_o14(8);
  fadcst(9) <= cst_o14(9);
  fadcst(10) <= cst_o14(10);
  fadcst(11) <= cst_o14(11);
  fadcst(12) <= cst_o14(12);
  fadcst(13) <= cst_o14(13);
  fadcst(14) <= cst_o14(14);
  fadcst(15) <= cst_o14(15);
end behavioural ;
