language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      before_install:
        - brew update
        - brew upgrade python

    - os: osx
      language: generic
      python: "2.7"


install:
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo apt-get -qq update || travis_terminate 1;
        sudo apt-get build-dep python-scipy || travis_terminate 1;  # deps for slycot
      else
        # install python requirements
        brew update;
        if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          brew install python;
          virtualenv venv -p python;
          source venv/bin/activate;
        else
          brew install python3;
          virtualenv venv -p python3;
          source venv/bin/activate;
        fi
      fi

# install required python packages for build and coverage
    - pip install pytest pytest-cov
    - pip install coveralls
    - python setup.py  install

script:
    - pytest -k construct --cov=fixif

notifications:
email: false

after_success:
    - if [[ $TOXENV == py36 ]]; then
          coveralls;
      fi
