language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - SOLLYA=true SLYCOT=true
  - SOLLYA=false  SLYCOT=false


matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      env:
        - SOLLYA=true
        - SLYCOT=true

#

before_install:
  # update apt-get or install python 3.6
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -qq update;
    else
      brew update;
      brew upgrade python;
      PATH=/usr/local/opt/python/libexec/bin:$PATH;
    fi

install:
  # install sollya (and prepare for slycot)
  - if "$SOLLYA"; then
        if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          wget https://gforge.inria.fr/frs/download.php/file/36270/sollya-6.0.tar.gz;
          tar xzf sollya-6.0.tar.gz;
          cd sollya-6.0/;
          ./configure && make -j4 && sudo make install;
          cd ..;
        else
          echo "Sollya not installed yet";
        fi
    fi
  # install slycot (first install requirement like gfortran and/or numpy/scipy)
  - if "$SLYCOT"; then
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get build-dep python-scipy || travis_terminate 1;
      else
        pip install numpy || travis_terminate 1;
        brew install gcc || brew link --overwrite gcc;
      fi;
      pip install slycot || travis_terminate 1;
    fi
  # install required python packages for build and coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  # and then install fixif
  - python setup.py  install

script:
    - pytest -k construct --cov=fixif

notifications:
email: false

after_success:
    # run coveralls for Python 3.6 under linux with Sollya and Slycot installed
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' && $SOLLYA && $SLYCOT && "$TRAVIS_OS_NAME" == "linux" ]]; then
          coveralls;
      fi
