language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      before_install:
        - brew update
        - brew upgrade python

    - os: osx
      language: generic
      python: "2.7"


before_install:
    - sudo apt-get -qq update
# install Slycot
    - sudo apt-get build-dep python-scipy
# install required python packages for build and coverage
    - pip install pytest pytest-cov
    - pip install coveralls
install:
    - python setup.py  install --process-dependency-links

script:
    - pytest -k construct --cov=fixif

notifications:
email: false

after_success:
    - if [[ $TOXENV == py36 ]]; then
          coveralls;
      fi
