language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - SOLLYA=true
  - SOLLYA=false
  - SLYCOT=true
  - SLYCOT=false


matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      before_install:
        - brew update
        # install python 3.6
        - brew upgrade python
        - PATH=/usr/local/opt/python/libexec/bin:$PATH


install:
  # install required python packages for build and coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  # install slycot if needed
  - if [[ $SLYCOT ]]; then
        pip install slycot;
    fi
  # and then install fixif
  - python setup.py  install

script:
    - pytest -k construct --cov=fixif

notifications:
email: false

after_success:
    # run coveralls for Python 3.6 under linux with Sollya and Slycot installed
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' && $SOLLYA && $SLYCOT && $TRAVIS_OS_NAME == 'linux' ]]; then
          coveralls;
      fi
