language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

include:
  - os: osx
    language: generic
    python: "3.6"
    before_install:
      - brew update
      - brew install python3
      - python3 -m venv venv
      - source venv/bin/activate
    install:
      - pip3 install --process-dependency-links

  - os: osx
    language: generic
    python: "2.7"
    install:
      - pip install --process-dependency-links



before_install:
    - sudo apt-get -qq update
# install Slycot
    - sudo apt-get build-dep python-scipy
# install required python packages for build and coverage
    - pip install pytest pytest-cov
    - pip install coveralls
install:
    - pip install --process-dependency-links

script:
    - pytest -k construct --cov=fixif

notifications:
email: false

after_success:
    - if [[ $TOXENV == py36 ]]; then
          coveralls;
      fi
