language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      before_install:
        - brew update
        # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
        - brew install openssl readline
        # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
        # I didn't do this above because it works and I'm lazy.
        - brew outdated pyenv || brew upgrade pyenv
        # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
        # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
        - brew install pyenv-virtualenv
        - pyenv install $PYTHON
        # I would expect something like ``pyenv init; pyenv local $PYTHON`` or
        # ``pyenv shell $PYTHON`` would work, but ``pyenv init`` doesn't seem to
        # modify the Bash environment. ??? So, I hand-set the variables instead.
        - export PYENV_VERSION=$PYTHON
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - pyenv-virtualenv venv
        - source venv/bin/activate
        # A manual check that the correct version of Python is running.
        - python --version


    - os: osx
      language: generic
      python: "2.7"
      before_install:
        - virtualenv venv -p python
        - source venv/bin/activate


install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    sudo apt-get -qq update || travis_terminate 1;
    sudo apt-get build-dep python-scipy || travis_terminate 1;
    fi
  # install required python packages for build and coverage
  - pip install pytest pytest-cov
  - pip install coveralls
  - python setup.py  install

script:
    - pytest -k construct --cov=fixif

notifications:
email: false

after_success:
    - if [[ $TOXENV == py36 ]]; then
          coveralls;
      fi
