language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
- SOLLYA=true  SLYCOT=true
- SOLLYA=false  SLYCOT=false


matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      before_install:
        - brew update
        # install python 3.6
        - brew upgrade python
        - PATH=/usr/local/opt/python/libexec/bin:$PATH
        # install numpy and gfortran (via gcc)
        - pip install numpy
        - brew install gcc || brew link --overwrite gcc

  exclude:
    - python: "3.4"
      SOLLYA=true
    - python: "3.5"
      SOLLYA=false

install:
  # install sollya (and prepare for slycot)
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      sudo apt-get -qq update || travis_terminate 1;
      sudo apt-get build-dep python-scipy || travis_terminate 1;
      if [[ $SOLLYA ]]; then
        sudo apt-get sollya;
      fi
      if [[ $SLYCOT ]]; then
        sudo pip install slycot;
      fi
    fi
  # install required python packages for build and coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py  install

script:
    - pytest -k construct --cov=fixif

notifications:
email: false

after_success:
    - if [[ $TOXENV == py36 ]]; then
          coveralls;
      fi
