language: python

#python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"

matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      before_install:
        - brew update
        - brew upgrade python
        - virtualenv venv
        - source venv/bin/activate
        - python --version
        - pip --version


    - os: osx
      language: generic
      python: "2.7"
      before_install:
        - virtualenv venv -p python
        - source venv/bin/activate
        - python --version
        - pip --update
        - pip --version



install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    sudo apt-get -qq update || travis_terminate 1;
    sudo apt-get build-dep python-scipy || travis_terminate 1;
    fi
  # install required python packages for build and coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py  install

script:
    - pytest -k construct --cov=fixif

notifications:
email: false

after_success:
    - if [[ $TOXENV == py36 ]]; then
          coveralls;
      fi
