language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

cache: pip

env:
  - SOLLYA=true SLYCOT=true
  - SOLLYA=false  SLYCOT=false


matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      env:
        - SOLLYA=true
        - SLYCOT=true

#

before_install:
  # update apt-get or install python 3.6
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -qq update;
    else
      brew update;
      brew upgrade python;
      brew install bison || brew link --overwrite bison;
      brew unlink libtool && brew uninstall libtool && brew install libtool;
      PATH=/usr/local/opt/bison/bin:/usr/local/opt/python/libexec/bin:$PATH;
    fi

install:
  # install sollya
  - if "$SOLLYA"; then

        if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          sudo apt-get install libmpfr-dev;
          sudo apt-get install libmpfi-dev;
        else
          brew install mpfi;
          sudo ln -s /usr/local/lib /lib;
        fi;

        git clone https://github.com/fplll/fplll.git;
        cd fplll;
        ./autogen.sh && ./configure && make -j&& sudo make install; cd ..;

        export LD_LIBRARY_PATH=/usr/local/lib;
        git clone https://scm.gforge.inria.fr/anonscm/git/sollya/sollya.git -b master sollya_git;
        cd sollya_git && sh autogen.sh && ./configure && make && sudo make install && cd ..;

        export PYTHON=python;
        pip install git+https://gitlab.com/metalibm-dev/pythonsollya;

    fi
  # install slycot (first install requirement like gfortran and/or numpy/scipy)
  - if "$SLYCOT"; then
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get build-dep python-scipy || travis_terminate 1;
      else
        pip install numpy || travis_terminate 1;
        brew install gcc || brew link --overwrite gcc;
      fi;
      pip install slycot || travis_terminate 1;
    fi
  # install WCPG and its python wrapper
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install f2c || travis_terminate 1;
      sudo apt-get install libmpfr-dev || travis_terminate 1;
      sudo apt-get install libmpfi-dev || travis_terminate 1;
      sudo apt-get build-dep python-scipy || travis_terminate 1;
    else
      brew install mpfi;
      pip install numpy;
      brew install gcc || brew link --overwrite gcc;
      wget http://hpc.sourceforge.net/buildf2c;
      sh buildf2c;
    fi
  - git clone https://github.com/fixif/WCPG.git
  - cd WCPG; sh autogen.sh && ./configure && make -j && sudo make install
  - export export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - python setup.py install; cd ..
  - pip list
  # install required python packages for build and coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  # and then install fixif
  - python setup.py  install

script:
    #- pytest -k construct --cov=fixif -s
    - if "$SOLLYA"; then
          pytest -v -k "(LTI and not WCPGmp) or (Structures and not simulink) and algorithmLaTeX" --cov=fixif fixif/;
      else
          pytest -v -k "(LTI and not Gabarit and not WCPGmp) or (Structures and not simulink) and algorithmLaTeX" --cov=fixif fixif/;
      fi

notifications:
email: false

after_success:
    # run coveralls for Python 3.6 under linux with Sollya and Slycot installed
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" && "$SOLLYA" && "$SLYCOT" && "$TRAVIS_OS_NAME" == "linux" ]]; then
          coveralls;
      fi
