[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fixif"
version = "0.5"
description = "Fixed-Point Filters"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "GPL3" }
authors = [{ name = "Thibault Hilaire", email = "thibault.hilaire@lip6.fr" }, { name = "Anastasia Volkova", email = "anastasia.volkova@inria.fr"}]
dependencies = [
    "pytest>=8.0",
    "pytest-cov>=5.0",
    "ruff>=0.4",
    "numpy",
    "scipy>=1.17",
    #"mpmath>=1.4",
    'python-flint',
    "slycot>=0.6",
    "matplotlib",
    "matplotlib2tikz",
    "scipy-stubs~=1.17.1",
]

[project.optional-dependencies]
dev = [
    "coverage>=7.14.1",
    "scipy-stubs~=1.17.1",
]

[tool.hatch.build.targets.wheel]
packages = ["fixif"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --tb=short"

[tool.coverage.run]
source = ["fixif/"]
omit = ["tests/*"]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP"]
ignore = [
    "N999",
    "N801",
    "N803",
    "N802",
    "N806",
]

