Bonmin: Bonmin::HeuristicDiveMIPVectorLength Class Reference
Bonmin::HeuristicDiveMIPVectorLength Class Reference
#include <BonHeuristicDiveMIPVectorLength.hpp>
Public Member Functions
HeuristicDiveMIPVectorLength ()
Default Constructor.
HeuristicDiveMIPVectorLength (BonminSetup *setup)
Constructor with setup.
HeuristicDiveMIPVectorLength (const HeuristicDiveMIPVectorLength &copy)
Copy constructor.
~HeuristicDiveMIPVectorLength ()
Destructor.
HeuristicDiveMIPVectorLength & operator= (const HeuristicDiveMIPVectorLength &rhs)
Assignment operator.
virtual CbcHeuristic * clone () const
Clone.
virtual void setSetup (BonminSetup *setup)
Change setup used for heuristic.
virtual void setInternalVariables (TMINLP2TNLP *minlp)
sets internal variables
virtual void selectVariableToBranch (TMINLP2TNLP *minlp, const vector< int > &integerColumns, const double *newSolution, int &bestColumn, int &bestRound)
Selects the next variable to branch on.
void Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Static Public Member Functions
static void registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register the options common to all local search based heuristics.
Private Attributes
int * columnLength_
the number of nonzero elements in each column
Detailed Description
Definition at line 21 of file BonHeuristicDiveMIPVectorLength.hpp.
Constructor & Destructor Documentation
Bonmin::HeuristicDiveMIPVectorLength::HeuristicDiveMIPVectorLength ()
Default Constructor.
Bonmin::HeuristicDiveMIPVectorLength::HeuristicDiveMIPVectorLength (BonminSetup * setup)
Constructor with setup.
Bonmin::HeuristicDiveMIPVectorLength::HeuristicDiveMIPVectorLength (const HeuristicDiveMIPVectorLength & copy)
Copy constructor.
Bonmin::HeuristicDiveMIPVectorLength::~HeuristicDiveMIPVectorLength () [inline]
Destructor.
Definition at line 33 of file BonHeuristicDiveMIPVectorLength.hpp.
References columnLength_.
Member Function Documentation
HeuristicDiveMIPVectorLength& Bonmin::HeuristicDiveMIPVectorLength::operator= (const HeuristicDiveMIPVectorLength & rhs)
Assignment operator.
Reimplemented from Bonmin::HeuristicDiveMIP.
virtual CbcHeuristic* Bonmin::HeuristicDiveMIPVectorLength::clone () const [virtual]
Clone.
Implements Bonmin::HeuristicDiveMIP.
virtual void Bonmin::HeuristicDiveMIPVectorLength::setSetup (BonminSetup * setup) [inline, virtual]
Change setup used for heuristic.
Reimplemented from Bonmin::HeuristicDiveMIP.
Definition at line 45 of file BonHeuristicDiveMIPVectorLength.hpp.
References Initialize(), and Bonmin::BabSetupBase::options().
virtual void Bonmin::HeuristicDiveMIPVectorLength::setInternalVariables (TMINLP2TNLP * minlp) [virtual]
sets internal variables
Implements Bonmin::HeuristicDiveMIP.
virtual void Bonmin::HeuristicDiveMIPVectorLength::selectVariableToBranch (TMINLP2TNLP * minlp, const vector< int > & integerColumns, const double * newSolution, int & bestColumn, int & bestRound) [virtual]
Selects the next variable to branch on.
If bestColumn = -1, it means that no variable was found
Implements Bonmin::HeuristicDiveMIP.
static void Bonmin::HeuristicDiveMIPVectorLength::registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static]
Register the options common to all local search based heuristics.
void Bonmin::HeuristicDiveMIPVectorLength::Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Referenced by setSetup().
Member Data Documentation
int* Bonmin::HeuristicDiveMIPVectorLength::columnLength_ [private]
the number of nonzero elements in each column
Definition at line 70 of file BonHeuristicDiveMIPVectorLength.hpp.
Referenced by ~HeuristicDiveMIPVectorLength().
The documentation for this class was generated from the following file:
BonHeuristicDiveMIPVectorLength.hpp