from genScalarProduct import scalarProduct
from dynMethodAdder import dynMethodAdder
from write_matrix_hex import write_matrix_hex
from python2mpf_matrix import python2mpf_matrix
from mpf_poly_mult import mpf_poly_mult
from mp_poly_product import mp_poly_product
from mpc_get_real import mpc_get_real
from mpf_to_numpy import mpf_to_numpy