from fixif.func_aux.genScalarProduct import scalarProduct
from fixif.func_aux.write_matrix_hex import write_matrix_hex
from fixif.func_aux.python2mpf_matrix import python2mpf_matrix
from fixif.func_aux.mpf_poly_mult import mpf_poly_mult
from fixif.func_aux.mp_poly_product import mp_poly_product
from fixif.func_aux.mpc_get_real import mpc_get_real
from fixif.func_aux.mpf_to_numpy import mpf_to_numpy
from fixif.func_aux.mpf_get_representation import mpf_get_representation
from fixif.func_aux.mpf_matrix_get_representation import mpf_matrix_get_representation
from fixif.func_aux.mpf_matrix_fmul import mpf_matrix_fmul
from fixif.func_aux.mpf_matrix_fadd import mpf_matrix_fadd
from fixif.func_aux.mpf_matrix_fsub import mpf_matrix_fsub
from fixif.func_aux.mpf_matrix_lt_inverse import  mpf_matrix_lt_inverse
from fixif.func_aux.mpf_matrix_to_sollya import mpf_matrix_to_sollya
from fixif.func_aux.sollya_matrix_print import sollya_matrix_print
from fixif.func_aux.MatlabHelper import MatlabHelper, isMatlabInstalled
from fixif.func_aux.MPFMatrix import MPFMatrix
from fixif.func_aux.sollya_matrix_to_numpy import sollya_matrix_to_numpy