library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.STD_LOGIC_arith.all;
use IEEE.STD_LOGIC_SIGNED.all;

-- purpose: filtering (generic fixed-point specificatin)
-- type   : sequential/arithmetic
-- inputs : u(n)
-- output : y(n) 
-- author : automatically generated by 
-- date   : 21-Mar-2011 14:28:19


package FP_types is

    -- input data with FP format (18,0,17)    subtype datain is integer range -2**17 to 2**17-1;    -- filtered output data with FP format (18,1,16)    subtype dataout is integer range -2**17 to 2**17-1;    -- states     subtype state1 is integer range -2**17 to 2**17-1;   -- format (18,1,16)    subtype state2 is integer range -2**17 to 2**17-1;   -- format (18,1,16)    subtype state3 is integer range -2**17 to 2**17-1;   -- format (18,1,16)    subtype state4 is integer range -2**17 to 2**17-1;   -- format (18,1,16)    subtype state5 is integer range -2**17 to 2**17-1;   -- format (18,1,16)    subtype state6 is integer range -2**17 to 2**17-1;   -- format (18,1,16)    subtype state7 is integer range -2**17 to 2**17-1;   -- format (18,0,17)    subtype state8 is integer range -2**17 to 2**17-1;   -- format (18,0,17)    subtype state9 is integer range -2**17 to 2**17-1;   -- format (18,0,17)    subtype state10 is integer range -2**17 to 2**17-1;   -- format (18,0,17)    subtype state11 is integer range -2**17 to 2**17-1;   -- format (18,0,17)    subtype state12 is integer range -2**17 to 2**17-1;   -- format (18,0,17)    -- intermediate variables     subtype intermediate_var1 is integer range -2**17 to 2**17-1;   -- format (18,-9,26)    subtype intermediate_var2 is integer range -2**17 to 2**17-1;   -- format (18,1,16)

end FP_types;
