% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
% y = filtreR3(u)
%
% y: filtered output(s)
% u: intput(s)
%
% date: 14-Feb-2008 12:01:17
% Automatically generated by implementMATLAB / FWRToolbox


function y = filtreR3(u)

% initialize                   
u = round(2^15*u);y = zeros( length(u), 1 );xn = zeros(16,1);                
                               
for i=1:length(u)

    % intermediate variables    Acc00 = xn( 1) * -14367;    Acc00 = Acc00 + xn( 2) * 22642;    Acc00 = Acc00 + xn( 3) * 3705;    Acc00 = Acc00 + xn( 4) * -6168;    Acc00 = Acc00 + u(i)   * 3705;    T0     = floor( Acc00/2^14 );    Acc01 = T0;    T1     = Acc01;    Acc02 = T1     * 14820;    Acc02 = Acc02 + xn( 5) * -27583;    Acc02 = Acc02 + xn( 6) * 27952;    Acc02 = Acc02 + xn( 7) * 14820;    Acc02 = Acc02 + xn( 8) * -7198;    T2     = floor( Acc02/2^15 );    Acc03 = T2;    T3     = Acc03;    Acc04 = T3     * 3705;    Acc04 = Acc04 + xn( 9) * -16064;    Acc04 = Acc04 + xn(10) * 26156;    Acc04 = Acc04 + xn(11) * 3705;    Acc04 = Acc04 + xn(12) * -6786;    T4     = floor( Acc04/2^14 );    Acc05 = T4;    T5     = Acc05;    Acc06 = T5     * 14820;    Acc06 = Acc06 + xn(13) * -31749;    Acc06 = Acc06 + xn(14) * 20428;    Acc06 = Acc06 + xn(15) * 14820;    Acc06 = Acc06 + xn(16) * 3514;    T6     = floor( Acc06/2^15 );    % states    Acc07 = xn( 2);    xn( 1) = Acc07;    Acc08 = T0;    xn( 2) = Acc08;    Acc09 = xn( 4);    xn( 3) = Acc09;    Acc10 = u(i);    xn( 4) = Acc10;    Acc11 = xn( 6);    xn( 5) = Acc11;    Acc12 = T2;    xn( 6) = Acc12;    Acc13 = xn( 8);    xn( 7) = Acc13;    Acc14 = T1;    xn( 8) = Acc14;    Acc15 = xn(10);    xn( 9) = Acc15;    Acc16 = T4;    xn(10) = Acc16;    Acc17 = xn(12);    xn(11) = Acc17;    Acc18 = T3;    xn(12) = Acc18;    Acc19 = xn(14);    xn(13) = Acc19;    Acc20 = T6;    xn(14) = Acc20;    Acc21 = xn(16);    xn(15) = Acc21;    Acc22 = T5;    xn(16) = Acc22;    % output(s)    Acc23 = T6;    y(i)   = Acc23;
    
end

y = 2^-13*y;