Bonmin: MyBonmin.cpp File Reference
MyBonmin.cpp File Reference
#include <iomanip>
#include <fstream>
#include "CoinPragma.hpp"
#include "CoinTime.hpp"
#include "CoinError.hpp"
#include "BonOsiTMINLPInterface.hpp"
#include "BonIpoptSolver.hpp"
#include "MyTMINLP.hpp"
#include "BonCbc.hpp"
#include "BonBonminSetup.hpp"
#include "BonOACutGenerator2.hpp"
#include "BonEcpCuts.hpp"
#include "BonOaNlpOptim.hpp"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 29 of file MyBonmin.cpp.
References Bonmin::BonminSetup::initialize(), Bonmin::BabSetupBase::initializeOptionsAndJournalist(), Bonmin::BabSetupBase::options(), Bonmin::BabSetupBase::readOptionsFile(), Bonmin::BabSetupBase::readOptionsString(), and Bonmin::BabSetupBase::roptions().