Bonmin: Bonmin::HeuristicDiveFractional Class Reference
Bonmin::HeuristicDiveFractional Class Reference
#include <BonHeuristicDiveFractional.hpp>
Public Member Functions
HeuristicDiveFractional ()
Default Constructor.
HeuristicDiveFractional (BonminSetup *setup)
Constructor with setup.
HeuristicDiveFractional (const HeuristicDiveFractional &copy)
Copy constructor.
~HeuristicDiveFractional ()
Destructor.
HeuristicDiveFractional & operator= (const HeuristicDiveFractional &rhs)
Assignment operator.
virtual CbcHeuristic * clone () const
Clone.
virtual void setSetup (BonminSetup *setup)
Change setup used for heuristic.
virtual void setInternalVariables (TMINLP2TNLP *minlp)
sets internal variables
virtual void selectVariableToBranch (TMINLP2TNLP *minlp, const vector< int > &integerColumns, const double *newSolution, int &bestColumn, int &bestRound)
Selects the next variable to branch on.
void Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Static Public Member Functions
static void registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions)
Register the options common to all local search based heuristics.
Detailed Description
Definition at line 21 of file BonHeuristicDiveFractional.hpp.
Constructor & Destructor Documentation
Bonmin::HeuristicDiveFractional::HeuristicDiveFractional ()
Default Constructor.
Bonmin::HeuristicDiveFractional::HeuristicDiveFractional (BonminSetup * setup)
Constructor with setup.
Bonmin::HeuristicDiveFractional::HeuristicDiveFractional (const HeuristicDiveFractional & copy)
Copy constructor.
Bonmin::HeuristicDiveFractional::~HeuristicDiveFractional () [inline]
Destructor.
Definition at line 33 of file BonHeuristicDiveFractional.hpp.
Member Function Documentation
HeuristicDiveFractional& Bonmin::HeuristicDiveFractional::operator= (const HeuristicDiveFractional & rhs)
Assignment operator.
Reimplemented from Bonmin::HeuristicDive.
virtual CbcHeuristic* Bonmin::HeuristicDiveFractional::clone () const [virtual]
Clone.
Implements Bonmin::HeuristicDive.
virtual void Bonmin::HeuristicDiveFractional::setSetup (BonminSetup * setup) [inline, virtual]
Change setup used for heuristic.
Reimplemented from Bonmin::HeuristicDive.
Definition at line 42 of file BonHeuristicDiveFractional.hpp.
References Initialize(), and Bonmin::BabSetupBase::options().
virtual void Bonmin::HeuristicDiveFractional::setInternalVariables (TMINLP2TNLP * minlp) [virtual]
sets internal variables
Implements Bonmin::HeuristicDive.
virtual void Bonmin::HeuristicDiveFractional::selectVariableToBranch (TMINLP2TNLP * minlp, const vector< int > & integerColumns, const double * newSolution, int & bestColumn, int & bestRound) [virtual]
Selects the next variable to branch on.
If bestColumn = -1, it means that no variable was found
Implements Bonmin::HeuristicDive.
static void Bonmin::HeuristicDiveFractional::registerOptions (Ipopt::SmartPtr< Bonmin::RegisteredOptions > roptions) [static]
Register the options common to all local search based heuristics.
void Bonmin::HeuristicDiveFractional::Initialize (Ipopt::SmartPtr< Ipopt::OptionsList > options)
Initiaize using passed options.
Referenced by setSetup().
The documentation for this class was generated from the following file:
BonHeuristicDiveFractional.hpp