% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
% y = filterR1(u)
%
% y: filtered output(s)
% u: intput(s)
%
% date: 14-May-2008 12:00:42
% Automatically generated by implementMATLAB / FWRToolbox


function y = filterR1(u)

% initialize                   
u = round(2.^10.*u);y = zeros( size(u,1), 1 );xn = zeros(2,1);xnp = zeros(2,1);                
                               
for i=1:size(u,1)

    % intermediate variables    Acc0 = xn(2) * -27433;    Acc0 = Acc0 + (u(i)) * 2^9;    xnp(1) = floor( Acc0/2^15 );    Acc1 = (xn(1)) * 2^14;    Acc1 = Acc1 + xn(2) * 29863;    xnp(2) = floor( Acc1/2^14 );    % output(s)    Acc2 = xn(1) * 14517;    Acc2 = Acc2 + xn(2) * 27079;    Acc2 = Acc2 + u(i)  * 59;    y(i)   = floor( Acc2/2^14 );    %permutations    xn = xnp;
    
end

y = 2.^-10.*y;