% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
% y = filterR2(u)
%
% y: filtered output(s)
% u: intput(s)
%
% date: 14-May-2008 12:00:55
% Automatically generated by implementMATLAB / FWRToolbox


function y = filterR2(u)

% initialize                   
u = round(2.^10.*u);y = zeros( size(u,1), 1 );xn = zeros(2,1);xnp = zeros(2,1);                
                               
for i=1:size(u,1)

    % intermediate variables    Acc0 = xn(1) * 28088;    Acc0 = Acc0 + xn(2) * 2964;    Acc0 = Acc0 + u(i)  * 6853;    xnp(1) = floor( Acc0/2^15 );    Acc1 = xn(1) * -3464;    Acc1 = Acc1 + xn(2) * 31638;    Acc1 = Acc1 + u(i)  * 234;    xnp(2) = floor( Acc1/2^15 );    % output(s)    Acc2 = xn(1) * 2899;    Acc2 = Acc2 + xn(2) * -21352;    Acc2 = Acc2 + u(i)  * 119;    y(i)   = floor( Acc2/2^15 );    %permutations    xn = xnp;
    
end

y = 2.^-10.*y;