/* this function is automatically generated by FiXiF
   from the Realization {{SIFname}}
   date: {{date}} */
{{OutVar}} {{funcName}}({{InVar}})
{
{{ExtraVar}}

	// intermediate variable(s)
{{InterComp}}

	//output(s)
{{OutComp}}

	//states
{{StatesComp}}

{{Permutations}}

{{return}}
}
