/* this file is automatically generated by FiPoGen v0.4
   from the Realization {{SIF.name}}
   date: {{date}} */

#include<stdio.h>

{{implementFunctions}}


/* call implementCdouble for each time step */
void runCdouble( double* u, double* y, int N)
{
	double xk[{{SIF.n}}]={0};
	for( int i=0; i<N; i++)
	{
		{{callImplementCdouble}}
		u += {{SIF.q}};
		y += {{SIF.p}};
	}
	printf("\n\n{{SIF._structureName}}!!\n\n\n");
}