% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
% y = balanced(u)
%
% y: filtered output(s)
% u: intput(s)
%
% date: 07-Dec-2007 14:37:11
% Automatically generated by implementMATLAB / FWRToolbox


function y = balanced(u)

% initialize                   
u = round(2^11*u);y = zeros( length(u), 1 );xn = zeros(6,1);xnp = zeros(6,1);                
                               
for i=1:length(u)

    % intermediate variables    Acc0 = xn(1) * 32370;    Acc0 = Acc0 + xn(2) * -3673;    Acc0 = Acc0 + xn(3) * 42;    Acc0 = Acc0 + xn(4) * 873;    Acc0 = Acc0 + xn(5) * -171;    Acc0 = Acc0 + xn(6) * 51;    Acc0 = Acc0 + u(i)  * 458;    xnp(1) = floor( Acc0/2^15 );    Acc1 = xn(1) * 3688;    Acc1 = Acc1 + xn(2) * 31858;    Acc1 = Acc1 + xn(3) * 4405;    Acc1 = Acc1 + xn(4) * 785;    Acc1 = Acc1 + xn(5) * -451;    Acc1 = Acc1 + xn(6) * 74;    Acc1 = Acc1 + u(i)  * -605;    xnp(2) = floor( Acc1/2^15 );    Acc2 = xn(1) * 318;    Acc2 = Acc2 + xn(2) * -4416;    Acc2 = Acc2 + xn(3) * 31250;    Acc2 = Acc2 + xn(4) * -3922;    Acc2 = Acc2 + xn(5) * 499;    Acc2 = Acc2 + xn(6) * -120;    Acc2 = Acc2 + u(i)  * -790;    xnp(3) = floor( Acc2/2^15 );    Acc3 = xn(1) * -900;    Acc3 = Acc3 + xn(2) * 546;    Acc3 = Acc3 + xn(3) * 3833;    Acc3 = Acc3 + xn(4) * 30304;    Acc3 = Acc3 + xn(5) * 1828;    Acc3 = Acc3 + xn(6) * -196;    Acc3 = Acc3 + u(i)  * 742;    xnp(4) = floor( Acc3/2^15 );    Acc4 = xn(1) * -551;    Acc4 = Acc4 + xn(2) * 1425;    Acc4 = Acc4 + xn(3) * 1760;    Acc4 = Acc4 + xn(4) * -7483;    Acc4 = Acc4 + xn(5) * 29956;    Acc4 = Acc4 + xn(6) * 1961;    Acc4 = Acc4 + u(i)  * 868;    xnp(5) = floor( Acc4/2^15 );    Acc5 = xn(1) * -786;    Acc5 = Acc5 + xn(2) * 1182;    Acc5 = Acc5 + xn(3) * 2572;    Acc5 = Acc5 + xn(4) * -4839;    Acc5 = Acc5 + xn(5) * -7995;    Acc5 = Acc5 + xn(6) * 29485;    Acc5 = Acc5 + u(i)  * 956;    xnp(6) = floor( Acc5/2^15 );    % output(s)    Acc6 = xn(1) * 14733;    Acc6 = Acc6 + xn(2) * 21060;    Acc6 = Acc6 + xn(3) * -23783;    Acc6 = Acc6 + xn(4) * -22615;    Acc6 = Acc6 + xn(5) * 7488;    Acc6 = Acc6 + xn(6) * -1780;    Acc6 = Acc6 + u(i)  * 77;    y(i)   = floor( Acc6/2^15 );    %permutations    xn = xnp;
    
end

y = 2^-10*y;