%==================================
% recursively process the directory
function processDir( matlab_dir, sub_matlab_dir, tex_dir, level)

endl=13;
tab='	';
section = { 'part', 'chapter', 'section', 'subsection', 'subsubsection', 'paragraph', 'subparagraph' };


% open/create the main files
if ~exist( fullfile(tex_dir, 'SimpleDoc', sub_matlab_dir) )
	mkdir( fullfile(tex_dir, 'SimpleDoc',sub_matlab_dir) );
end
mainfile = fopen( fullfile(tex_dir, 'SimpleDoc', sub_matlab_dir, 'main_SD.tex'), 'w');
tablefile = fopen( fullfile(tex_dir, 'SimpleDoc', sub_matlab_dir, 'table_SD.tex'), 'w');
fwrite( mainfile, ['% Generated by SimpleDoc (©T. Hilaire) - ' date endl endl]);
fwrite( tablefile, ['% Generated by SimpleDoc (©T. Hilaire) - ' date endl endl]);
fwrite( tablefile, ['\begin{longtable}{|p{3.4cm}|p{8.4cm}|}' endl]);

% process all the m-files
D = what(fullfile(matlab_dir,sub_matlab_dir));
D = D(1);
for i=1:length(D.m)
	% Process file D.m(i)
	texfileName=cell2mat(D.m(i));
	texfileName(end)='t';
	texfileName = [ texfileName 'ex'];
	fwrite( mainfile, [ '\input{SimpleDoc/' regexprep(sub_matlab_dir,'\\','/') '/' texfileName  '}' endl]);
	%fwrite( mainfile, [ '\input{' fullfile( 'SimpleDoc', sub_matlab_dir, texfileName ) '}' endl]); 
	processFile( fullfile(matlab_dir,sub_matlab_dir), fullfile(tex_dir,'SimpleDoc', sub_matlab_dir), texfileName(1:end-4), tablefile);
end


% process all the directory/classes
D = dir( fullfile(matlab_dir,sub_matlab_dir) );
for i=3:length(D)
	if D(i).isdir & D(i).name(1)~='.'
		% Process directory D(i).name
		processDir( matlab_dir, fullfile(sub_matlab_dir, D(i).name), tex_dir, level+1);
		if level>0
			fwrite( mainfile, [ endl '\' section{level} '{' D(i).name '}' endl ]);
			fwrite( mainfile, [ '\input{SimpleDoc/' regexprep(sub_matlab_dir,'\\','/') '/' D(i).name '/main_SD.tex}' endl]);			
			%fwrite( mainfile, [ '\input{' fullfile( 'SimpleDoc', sub_matlab_dir, D(i).name, 'main_SD.tex' ) '}' endl]);
		end
	end
end

% close the main files
fclose(mainfile);
fwrite( tablefile, [tab '\hline' endl '\end{longtable}' endl]);
fclose(tablefile);