/* this function is automatically generated by FiPoGen v0.4
   from the SIF {{SIFname}}
   date: {{date}} */
{{OutVar}} {{funcName}}({{InVar}})
{
{{ExtraVar}}

	// intermediate variable(s)
{{InterComp}}

	//output(s)
{{OutComp}}

	//states
{{StatesComp}}
{{Permutation}}

{{return}}
}