%Purpose:
% Create a LaTeX documentation from a collection of matlab files/classes.
% create two .tex files for each sub-directory
%("list_SD.tex" with the list of the functions and "table_SD.tex" with a table of the functions)
% and a .tex file for each function (they are called from the "list_SD.tex")
%
%Syntax:
% SimpleDoc( matlab_dir, tex_dir)
%
%Parameters:
% matlab_dir: matlab directory name (all its files and subdir will be added in the documentation)
% tex_dir: output directory name

%
%Example:
% the reference part of the FWRToolbox was generated by this tool is generated by
%
%	SimpleDoc( '../../FWRtoolbox', '../tex')
%   launched from "fwrtoolbox/doc/matlab" directory
%
%$Id$


function SimpleDoc( matlab_dir, tex_dir)

% source directory
if isdir(matlab_dir)==0
	error(['''' matlab_dir ''' is not a valid directory.']);
end

% destination directory
if isdir(tex_dir)==0
	error(['''' tex_dir ''' is not a valid directory.']);
end
if ~exist( fullfile( tex_dir, 'SimpleDoc') )
	mkdir (tex_dir, 'SimpleDoc');
end


% process
processDir( matlab_dir, '', tex_dir, -Inf);
%-Inf => do not include "\input{...}" for the next directories
%4 => include "\section{...}" and "\input{...}" the next directories
%for the FWRToolbox, the \section \input is done manually in order to
%add some introduction sentences








