--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity booth_mux is
  port(
      a    : IN std_logic;
      b    : IN std_logic;
      nul    : IN std_logic;
      comp    : IN std_logic;
      deca    : IN std_logic;
      pp    : OUT std_logic
  );
end booth_mux;



architecture behavioural of booth_mux is

component a2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


component inv_1
  port(
      i    : IN std_logic;
      nq    : OUT std_logic
  );
end component;


component o2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


component xr2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


signal bool_o0 : std_logic;
signal inv_o1 : std_logic;
signal bool_o2 : std_logic;
signal bool_o3 : std_logic;
signal bool_o4 : std_logic;
signal inv_o5 : std_logic;
signal bool_o6 : std_logic;
begin
  a2_1_i0 : a2_1
  port map(
       i1 => deca,
       i0 => a,
       q => bool_o0
  );
  inv_1_i1 : inv_1
  port map(
       i => deca,
       nq => inv_o1
  );
  a2_1_i2 : a2_1
  port map(
       i1 => b,
       i0 => inv_o1,
       q => bool_o2
  );
  o2_1_i3 : o2_1
  port map(
       i1 => bool_o2,
       i0 => bool_o0,
       q => bool_o3
  );
  xr2_1_i4 : xr2_1
  port map(
       i1 => comp,
       i0 => bool_o3,
       q => bool_o4
  );
  inv_1_i5 : inv_1
  port map(
       i => nul,
       nq => inv_o5
  );
  a2_1_i6 : a2_1
  port map(
       i1 => inv_o5,
       i0 => bool_o4,
       q => bool_o6
  );
  pp <= bool_o6;
end behavioural ;
