%Purpose:
% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
%Syntax:
% y = funR5(u)
%
%Parameters:
% y: filtered output(s)
% u: intput(s)
%
% date: 05-May-2011 15:14:52
% Automatically generated by implementMATLAB / FWRToolbox


function y = funR5(u)

% initialize                   
u = round(2.^6.*u);y = zeros( size(u,1), 1 );xn = zeros(2,1);                
                               
for i=1:size(u,1)

    % intermediate variables    Acc00 = xn(1) * -31;    Acc00 = Acc00 + xn(2) * 114;    Acc00 = Acc00 + u(i)  * -8;    T00   = floor( Acc00/2^7 );    Acc01 = xn(1) * -64;    Acc01 = Acc01 + xn(2) * -116;    Acc01 = Acc01 + u(i)  * -114;    T01   = floor( Acc01/2^8 );    % states    Acc02 = (T00) * 2^5;    Acc02 = Acc02 + (xn(1)) * 2^6;    xn(1) = floor( Acc02/2^6 );    Acc03 = (T01) * 2^5;    Acc03 = Acc03 + (xn(2)) * 2^6;    xn(2) = floor( Acc03/2^6 );    % output(s)    Acc04 = xn(1) * -92;    Acc04 = Acc04 + xn(2) * -31;    Acc04 = Acc04 + u(i)  * 3;    y(i)  = floor( Acc04/2^7 );
    
end

y = 2.^-6.*y;