%Purpose:
% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
%Syntax:
% y = funR3(u)
%
%Parameters:
% y: filtered output(s)
% u: intput(s)
%
% date: 05-May-2011 15:14:52
% Automatically generated by implementMATLAB / FWRToolbox


function y = funR3(u)

% initialize                   
u = round(2.^6.*u);y = zeros( size(u,1), 1 );xn = zeros(2,1);xnp = zeros(2,1);                
                               
for i=1:size(u,1)

    % intermediate variables    Acc00 = xn(1) * 113;    Acc00 = Acc00 + xn(2) * 30;    Acc00 = Acc00 + u(i)  * -25;    xnp(1) = floor( Acc00/2^7 );    Acc01 = xn(1) * -30;    Acc01 = Acc01 + xn(2) * 98;    Acc01 = Acc01 + u(i)  * -18;    xnp(2) = floor( Acc01/2^7 );    % output(s)    Acc02 = xn(1) * -102;    Acc02 = Acc02 + xn(2) * 73;    Acc02 = Acc02 + u(i)  * 3;    y(i)   = floor( Acc02/2^7 );    %permutations    xn = xnp;
    
end

y = 2.^-6.*y;