--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity booth_decoder is
  port(
      bminus    : IN std_logic;
      b    : IN std_logic;
      bplus    : IN std_logic;
      nul    : OUT std_logic;
      deca    : OUT std_logic;
      comp    : OUT std_logic
  );
end booth_decoder;



architecture behavioural of booth_decoder is

component inv_1
  port(
      i    : IN std_logic;
      nq    : OUT std_logic
  );
end component;


component a2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


component o2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


signal inv_o0 : std_logic;
signal inv_b : std_logic;
signal inv_o1 : std_logic;
signal inv_bplus : std_logic;
signal inv_o2 : std_logic;
signal inv_bminus : std_logic;
signal bool_o3 : std_logic;
signal bool_o4 : std_logic;
signal bool_o5 : std_logic;
signal bool_o6 : std_logic;
signal bool_o7 : std_logic;
signal bool_o8 : std_logic;
signal bool_o9 : std_logic;
signal bool_o10 : std_logic;
signal bool_o11 : std_logic;
signal bool_o12 : std_logic;
signal bool_o13 : std_logic;
signal bool_o14 : std_logic;
begin
  inv_1_i0 : inv_1
  port map(
       i => b,
       nq => inv_o0
  );
  inv_b <= inv_o0;
  inv_1_i1 : inv_1
  port map(
       i => bplus,
       nq => inv_o1
  );
  inv_bplus <= inv_o1;
  inv_1_i2 : inv_1
  port map(
       i => bminus,
       nq => inv_o2
  );
  inv_bminus <= inv_o2;
  a2_1_i3 : a2_1
  port map(
       i1 => b,
       i0 => bplus,
       q => bool_o3
  );
  a2_1_i4 : a2_1
  port map(
       i1 => bminus,
       i0 => bool_o3,
       q => bool_o4
  );
  a2_1_i5 : a2_1
  port map(
       i1 => inv_bplus,
       i0 => inv_b,
       q => bool_o5
  );
  a2_1_i6 : a2_1
  port map(
       i1 => inv_bminus,
       i0 => bool_o5,
       q => bool_o6
  );
  o2_1_i7 : o2_1
  port map(
       i1 => bool_o6,
       i0 => bool_o4,
       q => bool_o7
  );
  nul <= bool_o7;
  o2_1_i8 : o2_1
  port map(
       i1 => inv_bminus,
       i0 => inv_b,
       q => bool_o8
  );
  a2_1_i9 : a2_1
  port map(
       i1 => bool_o8,
       i0 => bplus,
       q => bool_o9
  );
  comp <= bool_o9;
  a2_1_i10 : a2_1
  port map(
       i1 => inv_bminus,
       i0 => inv_b,
       q => bool_o10
  );
  a2_1_i11 : a2_1
  port map(
       i1 => bplus,
       i0 => bool_o10,
       q => bool_o11
  );
  a2_1_i12 : a2_1
  port map(
       i1 => b,
       i0 => inv_bplus,
       q => bool_o12
  );
  a2_1_i13 : a2_1
  port map(
       i1 => bminus,
       i0 => bool_o12,
       q => bool_o13
  );
  o2_1_i14 : o2_1
  port map(
       i1 => bool_o13,
       i0 => bool_o11,
       q => bool_o14
  );
  deca <= bool_o14;
end behavioural ;
