--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity half_adder is
  port(
      a    : IN std_logic;
      b    : IN std_logic;
      sout    : OUT std_logic;
      cout    : OUT std_logic
  );
end half_adder;



architecture behavioural of half_adder is

component halfadder_x2
  port (
  a	: IN STD_LOGIC;
  b	: IN STD_LOGIC;
  cout	: OUT STD_LOGIC;
  sout	: OUT STD_LOGIC
);
end component;


begin
  halfadder_x2_i0 : halfadder_x2
  port map(
       a => a,
       cout => cout,
       b => b,
       sout => sout
  );
end behavioural ;
