--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity one_1 is
  port(
      q    : OUT std_logic
  );
end one_1;



architecture behavioural of one_1 is

component one_x0
  port (
  q	: OUT STD_LOGIC
);
end component;


begin
  one_x0_i0 : one_x0
  port map(
       q => q
  );
end behavioural ;
