% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
% y = myFilter(u)
%
% y: filtered output(s)
% u: intput(s)
%
% date: 25-Jul-2007 11:04:31
% Automatically generated by implementMATLAB / FWRToolbox


function y = myFilter(u)

% initialize                   
u = round(2^2*u);y = zeros( length(u), 1 );xn = zeros(2,1);                
                               
for i=1:length(u)

    % intermediate variables    Acc0 = (xn(1)) * 2^7;    Acc0 = Acc0 + (u(i)) * 2^5;    T0    = floor( Acc0/2^8 );    Acc1 = xn(2);    T1    = Acc1;    % states    Acc2 = T0    * -116;    Acc2 = Acc2 + (T1) * 2^6;    Acc2 = Acc2 + (xn(1)) * 2^5;    Acc2 = Acc2 + (u(i)) * 2^5;    xn(1) = floor( Acc2/2^5 );    Acc3 = T0    * -127;    Acc3 = Acc3 + (xn(2)) * 2^7;    Acc3 = Acc3 + (u(i)) * 2^6;    xn(2) = floor( Acc3/2^7 );    % output(s)    Acc4 = T0;    y(i)  = Acc4;
    
end

y = 2^-1*y;