library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.STD_LOGIC_arith.all;
use IEEE.STD_LOGIC_SIGNED.all;

-- purpose: filtering (generic fixed-point specificatin)
-- type   : sequential/arithmetic
-- inputs : u(n)
-- output : y(n) 
-- author : automatically generated by 
-- date   : 25-Jul-2007 11:18:04


package FP_types is

    -- input data with FP format (8,5,2)    subtype datain is integer range -2**7 to 2**7-1;    -- filtered output data with FP format (8,6,1)    subtype dataout is integer range -2**7 to 2**7-1;    -- states     subtype state1 is integer range -2**7 to 2**7-1;   -- format (8,10,-3)    subtype state2 is integer range -2**7 to 2**7-1;   -- format (8,16,-9)    -- intermediate variables     subtype intermediate_var1 is integer range -2**7 to 2**7-1;   -- format (8,6,1)    subtype intermediate_var2 is integer range -2**7 to 2**7-1;   -- format (8,11,-4)

end FP_types;
