library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.STD_LOGIC_arith.all;
use IEEE.STD_LOGIC_SIGNED.all;

-- purpose: filtering (generic fixed-point specificatin)
-- type   : sequential/arithmetic
-- inputs : u(n)
-- output : y(n) 
-- author : automatically generated by 
-- date   : 21-Dec-2007 11:12:46


package FP_types is

    -- input data with FP format (8,0,7)    subtype datain is integer range -2**7 to 2**7-1;    -- filtered output data with FP format (8,1,6)    subtype dataout is integer range -2**7 to 2**7-1;    -- states     subtype state1 is integer range -2**7 to 2**7-1;   -- format (8,6,1)    subtype state2 is integer range -2**7 to 2**7-1;   -- format (8,5,2)    subtype state3 is integer range -2**7 to 2**7-1;   -- format (8,3,4)    subtype state4 is integer range -2**7 to 2**7-1;   -- format (8,1,6)    subtype state5 is integer range -2**7 to 2**7-1;   -- format (8,-3,10)    -- intermediate variables     subtype intermediate_var1 is integer range -2**7 to 2**7-1;   -- format (8,1,6)    subtype intermediate_var2 is integer range -2**7 to 2**7-1;   -- format (8,0,7)    subtype intermediate_var3 is integer range -2**7 to 2**7-1;   -- format (8,-2,9)    subtype intermediate_var4 is integer range -2**7 to 2**7-1;   -- format (8,-4,11)    subtype intermediate_var5 is integer range -2**7 to 2**7-1;   -- format (8,-8,15)

end FP_types;
