library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.STD_LOGIC_arith.all;
use IEEE.STD_LOGIC_SIGNED.all;

-- purpose: filtering (generic fixed-point specificatin)
-- type   : sequential/arithmetic
-- inputs : u(n)
-- output : y(n) 
-- author : automatically generated by 
-- date   : 21-Dec-2007 11:12:00


package FP_types is

    -- input data with FP format (24,0,23)    subtype datain is integer range -2**23 to 2**23-1;    -- filtered output data with FP format (24,1,22)    subtype dataout is integer range -2**23 to 2**23-1;    -- states     subtype state1 is integer range -2**23 to 2**23-1;   -- format (24,6,17)    subtype state2 is integer range -2**23 to 2**23-1;   -- format (24,5,18)    subtype state3 is integer range -2**23 to 2**23-1;   -- format (24,3,20)    subtype state4 is integer range -2**23 to 2**23-1;   -- format (24,1,22)    subtype state5 is integer range -2**23 to 2**23-1;   -- format (24,-3,26)    -- intermediate variables     subtype intermediate_var1 is integer range -2**23 to 2**23-1;   -- format (24,1,22)    subtype intermediate_var2 is integer range -2**23 to 2**23-1;   -- format (24,0,23)    subtype intermediate_var3 is integer range -2**23 to 2**23-1;   -- format (24,-2,25)    subtype intermediate_var4 is integer range -2**23 to 2**23-1;   -- format (24,-4,27)    subtype intermediate_var5 is integer range -2**23 to 2**23-1;   -- format (24,-8,31)

end FP_types;
