%Purpose:
% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
%Syntax:
% y = funR6(u)
%
%Parameters:
% y: filtered output(s)
% u: intput(s)
%
% date: 05-May-2011 15:14:52
% Automatically generated by implementMATLAB / FWRToolbox


function y = funR6(u)

% initialize                   
u = round(2.^6.*u);y = zeros( size(u,1), 1 );xn = zeros(2,1);                
                               
for i=1:size(u,1)

    % intermediate variables    Acc00 = (xn(1)) * 2^6;    Acc00 = Acc00 + u(i);    T00   = floor( Acc00/2^6 );    Acc01 = xn(2);    T01   = Acc01;    % states    Acc02 = T00   * -22;    Acc02 = Acc02 + (T01) * 2^4;    Acc02 = Acc02 + (xn(1)) * 2^6;    Acc02 = Acc02 + u(i)  * 5;    xn(1) = floor( Acc02/2^6 );    Acc03 = T00   * -21;    Acc03 = Acc03 + (xn(2)) * 2^6;    Acc03 = Acc03 + u(i)  * 21;    xn(2) = floor( Acc03/2^6 );    % output(s)    Acc04 = T00;    y(i)  = Acc04;
    
end

y = 2.^-6.*y;