%Purpose:
% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
%Syntax:
% y = funR1(u)
%
%Parameters:
% y: filtered output(s)
% u: intput(s)
%
% date: 05-May-2011 15:14:51
% Automatically generated by implementMATLAB / FWRToolbox


function y = funR1(u)

% initialize                   
u = round(2.^6.*u);y = zeros( size(u,1), 1 );xn = zeros(4,1);                
                               
for i=1:size(u,1)

    % intermediate variables    Acc00 = xn(1) * -47;    Acc00 = Acc00 + xn(2) * 106;    Acc00 = Acc00 + xn(3);    Acc00 = Acc00 + xn(4) * 3;    Acc00 = Acc00 + u(i);    T00   = floor( Acc00/2^6 );    % states    Acc01 = xn(2);    xn(1) = Acc01;    Acc02 = T00;    xn(2) = Acc02;    Acc03 = xn(4);    xn(3) = Acc03;    Acc04 = u(i);    xn(4) = Acc04;    % output(s)    Acc05 = T00;    y(i)  = Acc05;
    
end

y = 2.^-6.*y;