%Purpose:
% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
%Syntax:
% y = funR2(u)
%
%Parameters:
% y: filtered output(s)
% u: intput(s)
%
% date: 05-May-2011 15:14:52
% Automatically generated by implementMATLAB / FWRToolbox


function y = funR2(u)

% initialize                   
u = round(2.^6.*u);y = zeros( size(u,1), 1 );xn = zeros(2,1);xnp = zeros(2,1);                
                               
for i=1:size(u,1)

    % intermediate variables    Acc00 = xn(1) * 106;    Acc00 = Acc00 + xn(2) * -47;    Acc00 = Acc00 + (u(i)) * 2^2;    xnp(1) = floor( Acc00/2^6 );    Acc01 = xn(1);    xnp(2) = Acc01;    % output(s)    Acc02 = xn(1) * 78;    Acc02 = Acc02 + xn(2) * 6;    Acc02 = Acc02 + u(i);    y(i)   = floor( Acc02/2^6 );    %permutations    xn = xnp;
    
end

y = 2.^-6.*y;