--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity add16 is
  port(
      i0    : IN std_logic_vector( 15 downto 0);
      i1    : IN std_logic_vector( 15 downto 0);
      o    : OUT std_logic_vector( 15 downto 0)
  );
end add16;



architecture behavioural of add16 is

component pigibus16
  port(
      a    : IN std_logic_vector( 15 downto 0);
      b    : IN std_logic_vector( 15 downto 0);
      pi    : OUT std_logic_vector( 15 downto 0);
      gi    : OUT std_logic_vector( 15 downto 0)
  );
end component;


component pgtree16slansky
  port(
      pi    : IN std_logic_vector( 15 downto 0);
      gi    : IN std_logic_vector( 15 downto 0);
      p    : OUT std_logic_vector( 15 downto 0);
      g    : OUT std_logic_vector( 15 downto 0)
  );
end component;


component buf_1
  port(
      i    : IN std_logic;
      q    : OUT std_logic
  );
end component;


component xr2_1
  port(
      i0    : IN std_logic;
      i1    : IN std_logic;
      q    : OUT std_logic
  );
end component;


signal pi3_a : std_logic_vector( 15 downto 0);
signal gi3_a : std_logic_vector( 15 downto 0);
signal p3_a : std_logic_vector( 15 downto 0);
signal g3_a : std_logic_vector( 15 downto 0);
signal buf_o0 : std_logic;
signal bool_o1 : std_logic;
signal bool_o2 : std_logic;
signal bool_o3 : std_logic;
signal bool_o4 : std_logic;
signal bool_o5 : std_logic;
signal bool_o6 : std_logic;
signal bool_o7 : std_logic;
signal bool_o8 : std_logic;
signal bool_o9 : std_logic;
signal bool_o10 : std_logic;
signal bool_o11 : std_logic;
signal bool_o12 : std_logic;
signal bool_o13 : std_logic;
signal bool_o14 : std_logic;
signal bool_o15 : std_logic;
begin
  pigibus16_i0 : pigibus16
  port map(
       a => i0,
       b => i1,
       pi => pi3_a,
       gi => gi3_a
  );
  pgtree16slansky_i1 : pgtree16slansky
  port map(
       g => g3_a,
       p => p3_a,
       pi => pi3_a,
       gi => gi3_a
  );
  buf_1_i2 : buf_1
  port map(
       q => buf_o0,
       i => pi3_a(0)
  );
  o(0) <= buf_o0;
  xr2_1_i3 : xr2_1
  port map(
       i1 => g3_a(0),
       i0 => pi3_a(1),
       q => bool_o1
  );
  o(1) <= bool_o1;
  xr2_1_i4 : xr2_1
  port map(
       i1 => g3_a(1),
       i0 => pi3_a(2),
       q => bool_o2
  );
  o(2) <= bool_o2;
  xr2_1_i5 : xr2_1
  port map(
       i1 => g3_a(2),
       i0 => pi3_a(3),
       q => bool_o3
  );
  o(3) <= bool_o3;
  xr2_1_i6 : xr2_1
  port map(
       i1 => g3_a(3),
       i0 => pi3_a(4),
       q => bool_o4
  );
  o(4) <= bool_o4;
  xr2_1_i7 : xr2_1
  port map(
       i1 => g3_a(4),
       i0 => pi3_a(5),
       q => bool_o5
  );
  o(5) <= bool_o5;
  xr2_1_i8 : xr2_1
  port map(
       i1 => g3_a(5),
       i0 => pi3_a(6),
       q => bool_o6
  );
  o(6) <= bool_o6;
  xr2_1_i9 : xr2_1
  port map(
       i1 => g3_a(6),
       i0 => pi3_a(7),
       q => bool_o7
  );
  o(7) <= bool_o7;
  xr2_1_i10 : xr2_1
  port map(
       i1 => g3_a(7),
       i0 => pi3_a(8),
       q => bool_o8
  );
  o(8) <= bool_o8;
  xr2_1_i11 : xr2_1
  port map(
       i1 => g3_a(8),
       i0 => pi3_a(9),
       q => bool_o9
  );
  o(9) <= bool_o9;
  xr2_1_i12 : xr2_1
  port map(
       i1 => g3_a(9),
       i0 => pi3_a(10),
       q => bool_o10
  );
  o(10) <= bool_o10;
  xr2_1_i13 : xr2_1
  port map(
       i1 => g3_a(10),
       i0 => pi3_a(11),
       q => bool_o11
  );
  o(11) <= bool_o11;
  xr2_1_i14 : xr2_1
  port map(
       i1 => g3_a(11),
       i0 => pi3_a(12),
       q => bool_o12
  );
  o(12) <= bool_o12;
  xr2_1_i15 : xr2_1
  port map(
       i1 => g3_a(12),
       i0 => pi3_a(13),
       q => bool_o13
  );
  o(13) <= bool_o13;
  xr2_1_i16 : xr2_1
  port map(
       i1 => g3_a(13),
       i0 => pi3_a(14),
       q => bool_o14
  );
  o(14) <= bool_o14;
  xr2_1_i17 : xr2_1
  port map(
       i1 => g3_a(14),
       i0 => pi3_a(15),
       q => bool_o15
  );
  o(15) <= bool_o15;
end behavioural ;
