--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity inv_1 is
  port(
      i    : IN std_logic;
      nq    : OUT std_logic
  );
end inv_1;



architecture behavioural of inv_1 is

component inv_x1
  port (
  i	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
);
end component;


begin
  inv_x1_i0 : inv_x1
  port map(
       i => i,
       nq => nq
  );
end behavioural ;
