--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity top_cell is
  port(
      oo    : OUT std_logic_vector( 15 downto 0);
      i0    : IN std_logic_vector( 15 downto 0);
      i1    : IN std_logic_vector( 15 downto 0);
      i2    : IN std_logic_vector( 15 downto 0);
      i3    : IN std_logic_vector( 15 downto 0)
  );
end top_cell;



architecture behavioural of top_cell is

component add_add_2
  port (
      oo    : OUT std_logic_vector( 15 downto 0);
      i0    : IN std_logic_vector( 15 downto 0);
      i1    : IN std_logic_vector( 15 downto 0);
      i2    : IN std_logic_vector( 15 downto 0);
      i3    : IN std_logic_vector( 15 downto 0)
);
end component;


signal inter : std_logic_vector( 15 downto 0);
begin
  iop : add_add_2
  port map(
       oo => inter,
       i1 => i1,
       i0 => i0,
       i3 => i3,
       i2 => i2
  );
  oo(0) <= inter(0);
  oo(1) <= inter(1);
  oo(2) <= inter(2);
  oo(3) <= inter(3);
  oo(4) <= inter(4);
  oo(5) <= inter(5);
  oo(6) <= inter(6);
  oo(7) <= inter(7);
  oo(8) <= inter(8);
  oo(9) <= inter(9);
  oo(10) <= inter(10);
  oo(11) <= inter(11);
  oo(12) <= inter(12);
  oo(13) <= inter(13);
  oo(14) <= inter(14);
  oo(15) <= inter(15);
end behavioural ;
