%Purpose:
% Fixed-point algorithm in Matlab language
% (it uses integer to simulate fixed-point)
%
%Syntax:
% y = filterR124q(u)
%
%Parameters:
% y: filtered output(s)
% u: intput(s)
%
% date: 07-Feb-2011 00:04:31
% Automatically generated by implementMATLAB / FWRToolbox


function y = filterR124q(u)

% initialize                   
u = round(2.^19.*u);
y = zeros( size(u,1), 1 );
xn = zeros(6,1);
                
                               
for i=1:size(u,1)


    % intermediate variables
    Acc0 = xn(4) * 5778218;
    Acc0 = Acc0 + xn(5) * -5774173;
    Acc0 = Acc0 + xn(6) * -5774173;
    Acc0 = Acc0 + u(i)  * 5778218;
    T0    = rem( floor( Acc0/2^24 ), 2^23);
    Acc1 = floor( (xn(1) * 8284039) / 2^2 );
    Acc1 = Acc1 + xn(2) * -6238941;
    Acc1 = Acc1 + xn(3) * 6265082;
    T1    = rem( floor( Acc1/2^21 ), 2^23);

    % states
    Acc2 = xn(2);
    xn(1) = Acc2;
    Acc3 = xn(3);
    xn(2) = Acc3;
    Acc4 = T0;
    Acc4 = Acc4 + (T1) * 2^10;
    xn(3) = rem( floor( Acc4/2^10 ), 2^23);
    Acc5 = xn(5);
    xn(4) = Acc5;
    Acc6 = xn(6);
    xn(5) = Acc6;
    Acc7 = u(i);
    xn(6) = Acc7;

    % output(s)
    Acc8 = T0;
    Acc8 = Acc8 + (T1) * 2^10;
    y(i)  = rem( floor( Acc8/2^10 ), 2^23);
    
end

y = 2.^-19.*y;
