function Measures( R )

[op_plus op_mul] = computationalCost(R);

disp( [ 'Msens=' num2str(MsensH(R)) ...
		' , error_tf=' num2str(error_tf(R)) ...
		' , Mpole=' num2str(MsensPole(R)) ...
		' , Nbop=' num2str(op_plus) '+ ' num2str(op_mul) 'x' ] )