library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.STD_LOGIC_arith.all;
use IEEE.STD_LOGIC_SIGNED.all;

-- purpose: filtering (generic fixed-point specificatin)
-- type   : sequential/arithmetic
-- inputs : u(n)
-- output : v(n) 
-- author : automatically generated by 
-- date   : 16-Jul-2007 13:33:37


package FP_types is

    -- input data with FP format (15,4,10)    subtype datain is integer range -2**14 to 2**14-1;    -- filtered output data with FP format (15,5,9)    subtype dataout is integer range -2**14 to 2**14-1;    -- states     subtype state1 is integer range -2**14 to 2**14-1;   -- format (15,9,5)    subtype state2 is integer range -2**14 to 2**14-1;   -- format (15,13,1)    subtype state3 is integer range -2**14 to 2**14-1;   -- format (15,14,0)    subtype state4 is integer range -2**14 to 2**14-1;   -- format (15,14,0)    -- intermediate variables     subtype intermediate_var1 is integer range -2**14 to 2**14-1;   -- format (15,5,9)    subtype intermediate_var2 is integer range -2**14 to 2**14-1;   -- format (15,9,5)    subtype intermediate_var3 is integer range -2**14 to 2**14-1;   -- format (15,10,4)    subtype intermediate_var4 is integer range -2**14 to 2**14-1;   -- format (15,10,4)    -- accumulators     subtype accumulator1 is integer range -2**29 to 2**29-1;   -- format (30,6,23)    subtype accumulator2 is integer range -2**29 to 2**29-1;   -- format (30,10,19)    subtype accumulator3 is integer range -2**29 to 2**29-1;   -- format (30,11,18)    subtype accumulator4 is integer range -2**29 to 2**29-1;   -- format (30,11,18)    subtype accumulator5 is integer range -2**29 to 2**29-1;   -- format (30,11,18)    subtype accumulator6 is integer range -2**29 to 2**29-1;   -- format (30,14,15)    subtype accumulator7 is integer range -2**29 to 2**29-1;   -- format (30,15,14)    subtype accumulator8 is integer range -2**29 to 2**29-1;   -- format (30,15,14)    subtype accumulator9 is integer range -2**29 to 2**29-1;   -- format (30,5,24)

end FP_types;
