--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity pgtree16slansky is
  port(
      pi    : IN std_logic_vector( 15 downto 0);
      gi    : IN std_logic_vector( 15 downto 0);
      p    : OUT std_logic_vector( 15 downto 0);
      g    : OUT std_logic_vector( 15 downto 0)
  );
end pgtree16slansky;



architecture behavioural of pgtree16slansky is

component buf_1
  port(
      i    : IN std_logic;
      q    : OUT std_logic
  );
end component;


component pg
  port(
      p1    : IN std_logic;
      g1    : IN std_logic;
      p2    : IN std_logic;
      g2    : IN std_logic;
      p    : OUT std_logic;
      g    : OUT std_logic
  );
end component;


component buf_16
  port(
      i    : IN std_logic_vector( 15 downto 0);
      q    : OUT std_logic_vector( 15 downto 0)
  );
end component;


signal p1 : std_logic_vector( 15 downto 0);
signal g1 : std_logic_vector( 15 downto 0);
signal buf_o0 : std_logic;
signal buf_o1 : std_logic;
signal buf_o2 : std_logic;
signal buf_o3 : std_logic;
signal buf_o4 : std_logic;
signal buf_o5 : std_logic;
signal buf_o6 : std_logic;
signal buf_o7 : std_logic;
signal buf_o8 : std_logic;
signal buf_o9 : std_logic;
signal buf_o10 : std_logic;
signal buf_o11 : std_logic;
signal buf_o12 : std_logic;
signal buf_o13 : std_logic;
signal buf_o14 : std_logic;
signal buf_o15 : std_logic;
signal p2 : std_logic_vector( 15 downto 0);
signal g2 : std_logic_vector( 15 downto 0);
signal buf_o16 : std_logic;
signal buf_o17 : std_logic;
signal buf_o18 : std_logic;
signal buf_o19 : std_logic;
signal buf_o20 : std_logic;
signal buf_o21 : std_logic;
signal buf_o22 : std_logic;
signal buf_o23 : std_logic;
signal buf_o24 : std_logic;
signal buf_o25 : std_logic;
signal buf_o26 : std_logic;
signal buf_o27 : std_logic;
signal buf_o28 : std_logic;
signal buf_o29 : std_logic;
signal buf_o30 : std_logic;
signal buf_o31 : std_logic;
signal p3 : std_logic_vector( 15 downto 0);
signal g3 : std_logic_vector( 15 downto 0);
signal buf_o32 : std_logic;
signal buf_o33 : std_logic;
signal buf_o34 : std_logic;
signal buf_o35 : std_logic;
signal buf_o36 : std_logic;
signal buf_o37 : std_logic;
signal buf_o38 : std_logic;
signal buf_o39 : std_logic;
signal buf_o40 : std_logic;
signal buf_o41 : std_logic;
signal buf_o42 : std_logic;
signal buf_o43 : std_logic;
signal buf_o44 : std_logic;
signal buf_o45 : std_logic;
signal buf_o46 : std_logic;
signal buf_o47 : std_logic;
signal p4 : std_logic_vector( 15 downto 0);
signal g4 : std_logic_vector( 15 downto 0);
signal buf_o48 : std_logic;
signal buf_o49 : std_logic;
signal buf_o50 : std_logic;
signal buf_o51 : std_logic;
signal buf_o52 : std_logic;
signal buf_o53 : std_logic;
signal buf_o54 : std_logic;
signal buf_o55 : std_logic;
signal buf_o56 : std_logic;
signal buf_o57 : std_logic;
signal buf_o58 : std_logic;
signal buf_o59 : std_logic;
signal buf_o60 : std_logic;
signal buf_o61 : std_logic;
signal buf_o62 : std_logic;
signal buf_o63 : std_logic;
signal buf_o64 : std_logic_vector( 15 downto 0);
signal buf_o65 : std_logic_vector( 15 downto 0);
begin
  buf_1_i0 : buf_1
  port map(
       q => buf_o0,
       i => pi(0)
  );
  p1(0) <= buf_o0;
  buf_1_i1 : buf_1
  port map(
       q => buf_o1,
       i => gi(0)
  );
  g1(0) <= buf_o1;
  pg_i2 : pg
  port map(
       p2 => pi(0),
       p => p1(1),
       p1 => pi(1),
       g => g1(1),
       g2 => gi(0),
       g1 => gi(1)
  );
  buf_1_i3 : buf_1
  port map(
       q => buf_o2,
       i => pi(2)
  );
  p1(2) <= buf_o2;
  buf_1_i4 : buf_1
  port map(
       q => buf_o3,
       i => gi(2)
  );
  g1(2) <= buf_o3;
  pg_i5 : pg
  port map(
       p2 => pi(2),
       p => p1(3),
       p1 => pi(3),
       g => g1(3),
       g2 => gi(2),
       g1 => gi(3)
  );
  buf_1_i6 : buf_1
  port map(
       q => buf_o4,
       i => pi(4)
  );
  p1(4) <= buf_o4;
  buf_1_i7 : buf_1
  port map(
       q => buf_o5,
       i => gi(4)
  );
  g1(4) <= buf_o5;
  pg_i8 : pg
  port map(
       p2 => pi(4),
       p => p1(5),
       p1 => pi(5),
       g => g1(5),
       g2 => gi(4),
       g1 => gi(5)
  );
  buf_1_i9 : buf_1
  port map(
       q => buf_o6,
       i => pi(6)
  );
  p1(6) <= buf_o6;
  buf_1_i10 : buf_1
  port map(
       q => buf_o7,
       i => gi(6)
  );
  g1(6) <= buf_o7;
  pg_i11 : pg
  port map(
       p2 => pi(6),
       p => p1(7),
       p1 => pi(7),
       g => g1(7),
       g2 => gi(6),
       g1 => gi(7)
  );
  buf_1_i12 : buf_1
  port map(
       q => buf_o8,
       i => pi(8)
  );
  p1(8) <= buf_o8;
  buf_1_i13 : buf_1
  port map(
       q => buf_o9,
       i => gi(8)
  );
  g1(8) <= buf_o9;
  pg_i14 : pg
  port map(
       p2 => pi(8),
       p => p1(9),
       p1 => pi(9),
       g => g1(9),
       g2 => gi(8),
       g1 => gi(9)
  );
  buf_1_i15 : buf_1
  port map(
       q => buf_o10,
       i => pi(10)
  );
  p1(10) <= buf_o10;
  buf_1_i16 : buf_1
  port map(
       q => buf_o11,
       i => gi(10)
  );
  g1(10) <= buf_o11;
  pg_i17 : pg
  port map(
       p2 => pi(10),
       p => p1(11),
       p1 => pi(11),
       g => g1(11),
       g2 => gi(10),
       g1 => gi(11)
  );
  buf_1_i18 : buf_1
  port map(
       q => buf_o12,
       i => pi(12)
  );
  p1(12) <= buf_o12;
  buf_1_i19 : buf_1
  port map(
       q => buf_o13,
       i => gi(12)
  );
  g1(12) <= buf_o13;
  pg_i20 : pg
  port map(
       p2 => pi(12),
       p => p1(13),
       p1 => pi(13),
       g => g1(13),
       g2 => gi(12),
       g1 => gi(13)
  );
  buf_1_i21 : buf_1
  port map(
       q => buf_o14,
       i => pi(14)
  );
  p1(14) <= buf_o14;
  buf_1_i22 : buf_1
  port map(
       q => buf_o15,
       i => gi(14)
  );
  g1(14) <= buf_o15;
  pg_i23 : pg
  port map(
       p2 => pi(14),
       p => p1(15),
       p1 => pi(15),
       g => g1(15),
       g2 => gi(14),
       g1 => gi(15)
  );
  buf_1_i24 : buf_1
  port map(
       q => buf_o16,
       i => p1(0)
  );
  p2(0) <= buf_o16;
  buf_1_i25 : buf_1
  port map(
       q => buf_o17,
       i => g1(0)
  );
  g2(0) <= buf_o17;
  buf_1_i26 : buf_1
  port map(
       q => buf_o18,
       i => p1(1)
  );
  p2(1) <= buf_o18;
  buf_1_i27 : buf_1
  port map(
       q => buf_o19,
       i => g1(1)
  );
  g2(1) <= buf_o19;
  pg_i28 : pg
  port map(
       p2 => p1(1),
       p => p2(2),
       p1 => p1(2),
       g => g2(2),
       g2 => g1(1),
       g1 => g1(2)
  );
  pg_i29 : pg
  port map(
       p2 => p1(1),
       p => p2(3),
       p1 => p1(3),
       g => g2(3),
       g2 => g1(1),
       g1 => g1(3)
  );
  buf_1_i30 : buf_1
  port map(
       q => buf_o20,
       i => p1(4)
  );
  p2(4) <= buf_o20;
  buf_1_i31 : buf_1
  port map(
       q => buf_o21,
       i => g1(4)
  );
  g2(4) <= buf_o21;
  buf_1_i32 : buf_1
  port map(
       q => buf_o22,
       i => p1(5)
  );
  p2(5) <= buf_o22;
  buf_1_i33 : buf_1
  port map(
       q => buf_o23,
       i => g1(5)
  );
  g2(5) <= buf_o23;
  pg_i34 : pg
  port map(
       p2 => p1(5),
       p => p2(6),
       p1 => p1(6),
       g => g2(6),
       g2 => g1(5),
       g1 => g1(6)
  );
  pg_i35 : pg
  port map(
       p2 => p1(5),
       p => p2(7),
       p1 => p1(7),
       g => g2(7),
       g2 => g1(5),
       g1 => g1(7)
  );
  buf_1_i36 : buf_1
  port map(
       q => buf_o24,
       i => p1(8)
  );
  p2(8) <= buf_o24;
  buf_1_i37 : buf_1
  port map(
       q => buf_o25,
       i => g1(8)
  );
  g2(8) <= buf_o25;
  buf_1_i38 : buf_1
  port map(
       q => buf_o26,
       i => p1(9)
  );
  p2(9) <= buf_o26;
  buf_1_i39 : buf_1
  port map(
       q => buf_o27,
       i => g1(9)
  );
  g2(9) <= buf_o27;
  pg_i40 : pg
  port map(
       p2 => p1(9),
       p => p2(10),
       p1 => p1(10),
       g => g2(10),
       g2 => g1(9),
       g1 => g1(10)
  );
  pg_i41 : pg
  port map(
       p2 => p1(9),
       p => p2(11),
       p1 => p1(11),
       g => g2(11),
       g2 => g1(9),
       g1 => g1(11)
  );
  buf_1_i42 : buf_1
  port map(
       q => buf_o28,
       i => p1(12)
  );
  p2(12) <= buf_o28;
  buf_1_i43 : buf_1
  port map(
       q => buf_o29,
       i => g1(12)
  );
  g2(12) <= buf_o29;
  buf_1_i44 : buf_1
  port map(
       q => buf_o30,
       i => p1(13)
  );
  p2(13) <= buf_o30;
  buf_1_i45 : buf_1
  port map(
       q => buf_o31,
       i => g1(13)
  );
  g2(13) <= buf_o31;
  pg_i46 : pg
  port map(
       p2 => p1(13),
       p => p2(14),
       p1 => p1(14),
       g => g2(14),
       g2 => g1(13),
       g1 => g1(14)
  );
  pg_i47 : pg
  port map(
       p2 => p1(13),
       p => p2(15),
       p1 => p1(15),
       g => g2(15),
       g2 => g1(13),
       g1 => g1(15)
  );
  buf_1_i48 : buf_1
  port map(
       q => buf_o32,
       i => p2(0)
  );
  p3(0) <= buf_o32;
  buf_1_i49 : buf_1
  port map(
       q => buf_o33,
       i => g2(0)
  );
  g3(0) <= buf_o33;
  buf_1_i50 : buf_1
  port map(
       q => buf_o34,
       i => p2(1)
  );
  p3(1) <= buf_o34;
  buf_1_i51 : buf_1
  port map(
       q => buf_o35,
       i => g2(1)
  );
  g3(1) <= buf_o35;
  buf_1_i52 : buf_1
  port map(
       q => buf_o36,
       i => p2(2)
  );
  p3(2) <= buf_o36;
  buf_1_i53 : buf_1
  port map(
       q => buf_o37,
       i => g2(2)
  );
  g3(2) <= buf_o37;
  buf_1_i54 : buf_1
  port map(
       q => buf_o38,
       i => p2(3)
  );
  p3(3) <= buf_o38;
  buf_1_i55 : buf_1
  port map(
       q => buf_o39,
       i => g2(3)
  );
  g3(3) <= buf_o39;
  pg_i56 : pg
  port map(
       p2 => p2(3),
       p => p3(4),
       p1 => p2(4),
       g => g3(4),
       g2 => g2(3),
       g1 => g2(4)
  );
  pg_i57 : pg
  port map(
       p2 => p2(3),
       p => p3(5),
       p1 => p2(5),
       g => g3(5),
       g2 => g2(3),
       g1 => g2(5)
  );
  pg_i58 : pg
  port map(
       p2 => p2(3),
       p => p3(6),
       p1 => p2(6),
       g => g3(6),
       g2 => g2(3),
       g1 => g2(6)
  );
  pg_i59 : pg
  port map(
       p2 => p2(3),
       p => p3(7),
       p1 => p2(7),
       g => g3(7),
       g2 => g2(3),
       g1 => g2(7)
  );
  buf_1_i60 : buf_1
  port map(
       q => buf_o40,
       i => p2(8)
  );
  p3(8) <= buf_o40;
  buf_1_i61 : buf_1
  port map(
       q => buf_o41,
       i => g2(8)
  );
  g3(8) <= buf_o41;
  buf_1_i62 : buf_1
  port map(
       q => buf_o42,
       i => p2(9)
  );
  p3(9) <= buf_o42;
  buf_1_i63 : buf_1
  port map(
       q => buf_o43,
       i => g2(9)
  );
  g3(9) <= buf_o43;
  buf_1_i64 : buf_1
  port map(
       q => buf_o44,
       i => p2(10)
  );
  p3(10) <= buf_o44;
  buf_1_i65 : buf_1
  port map(
       q => buf_o45,
       i => g2(10)
  );
  g3(10) <= buf_o45;
  buf_1_i66 : buf_1
  port map(
       q => buf_o46,
       i => p2(11)
  );
  p3(11) <= buf_o46;
  buf_1_i67 : buf_1
  port map(
       q => buf_o47,
       i => g2(11)
  );
  g3(11) <= buf_o47;
  pg_i68 : pg
  port map(
       p2 => p2(11),
       p => p3(12),
       p1 => p2(12),
       g => g3(12),
       g2 => g2(11),
       g1 => g2(12)
  );
  pg_i69 : pg
  port map(
       p2 => p2(11),
       p => p3(13),
       p1 => p2(13),
       g => g3(13),
       g2 => g2(11),
       g1 => g2(13)
  );
  pg_i70 : pg
  port map(
       p2 => p2(11),
       p => p3(14),
       p1 => p2(14),
       g => g3(14),
       g2 => g2(11),
       g1 => g2(14)
  );
  pg_i71 : pg
  port map(
       p2 => p2(11),
       p => p3(15),
       p1 => p2(15),
       g => g3(15),
       g2 => g2(11),
       g1 => g2(15)
  );
  buf_1_i72 : buf_1
  port map(
       q => buf_o48,
       i => p3(0)
  );
  p4(0) <= buf_o48;
  buf_1_i73 : buf_1
  port map(
       q => buf_o49,
       i => g3(0)
  );
  g4(0) <= buf_o49;
  buf_1_i74 : buf_1
  port map(
       q => buf_o50,
       i => p3(1)
  );
  p4(1) <= buf_o50;
  buf_1_i75 : buf_1
  port map(
       q => buf_o51,
       i => g3(1)
  );
  g4(1) <= buf_o51;
  buf_1_i76 : buf_1
  port map(
       q => buf_o52,
       i => p3(2)
  );
  p4(2) <= buf_o52;
  buf_1_i77 : buf_1
  port map(
       q => buf_o53,
       i => g3(2)
  );
  g4(2) <= buf_o53;
  buf_1_i78 : buf_1
  port map(
       q => buf_o54,
       i => p3(3)
  );
  p4(3) <= buf_o54;
  buf_1_i79 : buf_1
  port map(
       q => buf_o55,
       i => g3(3)
  );
  g4(3) <= buf_o55;
  buf_1_i80 : buf_1
  port map(
       q => buf_o56,
       i => p3(4)
  );
  p4(4) <= buf_o56;
  buf_1_i81 : buf_1
  port map(
       q => buf_o57,
       i => g3(4)
  );
  g4(4) <= buf_o57;
  buf_1_i82 : buf_1
  port map(
       q => buf_o58,
       i => p3(5)
  );
  p4(5) <= buf_o58;
  buf_1_i83 : buf_1
  port map(
       q => buf_o59,
       i => g3(5)
  );
  g4(5) <= buf_o59;
  buf_1_i84 : buf_1
  port map(
       q => buf_o60,
       i => p3(6)
  );
  p4(6) <= buf_o60;
  buf_1_i85 : buf_1
  port map(
       q => buf_o61,
       i => g3(6)
  );
  g4(6) <= buf_o61;
  buf_1_i86 : buf_1
  port map(
       q => buf_o62,
       i => p3(7)
  );
  p4(7) <= buf_o62;
  buf_1_i87 : buf_1
  port map(
       q => buf_o63,
       i => g3(7)
  );
  g4(7) <= buf_o63;
  pg_i88 : pg
  port map(
       p2 => p3(7),
       p => p4(8),
       p1 => p3(8),
       g => g4(8),
       g2 => g3(7),
       g1 => g3(8)
  );
  pg_i89 : pg
  port map(
       p2 => p3(7),
       p => p4(9),
       p1 => p3(9),
       g => g4(9),
       g2 => g3(7),
       g1 => g3(9)
  );
  pg_i90 : pg
  port map(
       p2 => p3(7),
       p => p4(10),
       p1 => p3(10),
       g => g4(10),
       g2 => g3(7),
       g1 => g3(10)
  );
  pg_i91 : pg
  port map(
       p2 => p3(7),
       p => p4(11),
       p1 => p3(11),
       g => g4(11),
       g2 => g3(7),
       g1 => g3(11)
  );
  pg_i92 : pg
  port map(
       p2 => p3(7),
       p => p4(12),
       p1 => p3(12),
       g => g4(12),
       g2 => g3(7),
       g1 => g3(12)
  );
  pg_i93 : pg
  port map(
       p2 => p3(7),
       p => p4(13),
       p1 => p3(13),
       g => g4(13),
       g2 => g3(7),
       g1 => g3(13)
  );
  pg_i94 : pg
  port map(
       p2 => p3(7),
       p => p4(14),
       p1 => p3(14),
       g => g4(14),
       g2 => g3(7),
       g1 => g3(14)
  );
  pg_i95 : pg
  port map(
       p2 => p3(7),
       p => p4(15),
       p1 => p3(15),
       g => g4(15),
       g2 => g3(7),
       g1 => g3(15)
  );
  buf_16_i96 : buf_16
  port map(
       q => buf_o64,
       i => p4
  );
  p(0) <= buf_o64(0);
  p(1) <= buf_o64(1);
  p(2) <= buf_o64(2);
  p(3) <= buf_o64(3);
  p(4) <= buf_o64(4);
  p(5) <= buf_o64(5);
  p(6) <= buf_o64(6);
  p(7) <= buf_o64(7);
  p(8) <= buf_o64(8);
  p(9) <= buf_o64(9);
  p(10) <= buf_o64(10);
  p(11) <= buf_o64(11);
  p(12) <= buf_o64(12);
  p(13) <= buf_o64(13);
  p(14) <= buf_o64(14);
  p(15) <= buf_o64(15);
  buf_16_i97 : buf_16
  port map(
       q => buf_o65,
       i => g4
  );
  g(0) <= buf_o65(0);
  g(1) <= buf_o65(1);
  g(2) <= buf_o65(2);
  g(3) <= buf_o65(3);
  g(4) <= buf_o65(4);
  g(5) <= buf_o65(5);
  g(6) <= buf_o65(6);
  g(7) <= buf_o65(7);
  g(8) <= buf_o65(8);
  g(9) <= buf_o65(9);
  g(10) <= buf_o65(10);
  g(11) <= buf_o65(11);
  g(12) <= buf_o65(12);
  g(13) <= buf_o65(13);
  g(14) <= buf_o65(14);
  g(15) <= buf_o65(15);
end behavioural ;
