--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity buf_32 is
  port(
      i    : IN std_logic_vector( 31 downto 0);
      q    : OUT std_logic_vector( 31 downto 0)
  );
end buf_32;



architecture behavioural of buf_32 is

component buf_x2
  port (
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
);
end component;


begin
  buf_x2_i0 : buf_x2
  port map(
       i => i(0),
       q => q(0)
  );
  buf_x2_i1 : buf_x2
  port map(
       i => i(1),
       q => q(1)
  );
  buf_x2_i2 : buf_x2
  port map(
       i => i(2),
       q => q(2)
  );
  buf_x2_i3 : buf_x2
  port map(
       i => i(3),
       q => q(3)
  );
  buf_x2_i4 : buf_x2
  port map(
       i => i(4),
       q => q(4)
  );
  buf_x2_i5 : buf_x2
  port map(
       i => i(5),
       q => q(5)
  );
  buf_x2_i6 : buf_x2
  port map(
       i => i(6),
       q => q(6)
  );
  buf_x2_i7 : buf_x2
  port map(
       i => i(7),
       q => q(7)
  );
  buf_x2_i8 : buf_x2
  port map(
       i => i(8),
       q => q(8)
  );
  buf_x2_i9 : buf_x2
  port map(
       i => i(9),
       q => q(9)
  );
  buf_x2_i10 : buf_x2
  port map(
       i => i(10),
       q => q(10)
  );
  buf_x2_i11 : buf_x2
  port map(
       i => i(11),
       q => q(11)
  );
  buf_x2_i12 : buf_x2
  port map(
       i => i(12),
       q => q(12)
  );
  buf_x2_i13 : buf_x2
  port map(
       i => i(13),
       q => q(13)
  );
  buf_x2_i14 : buf_x2
  port map(
       i => i(14),
       q => q(14)
  );
  buf_x2_i15 : buf_x2
  port map(
       i => i(15),
       q => q(15)
  );
  buf_x2_i16 : buf_x2
  port map(
       i => i(16),
       q => q(16)
  );
  buf_x2_i17 : buf_x2
  port map(
       i => i(17),
       q => q(17)
  );
  buf_x2_i18 : buf_x2
  port map(
       i => i(18),
       q => q(18)
  );
  buf_x2_i19 : buf_x2
  port map(
       i => i(19),
       q => q(19)
  );
  buf_x2_i20 : buf_x2
  port map(
       i => i(20),
       q => q(20)
  );
  buf_x2_i21 : buf_x2
  port map(
       i => i(21),
       q => q(21)
  );
  buf_x2_i22 : buf_x2
  port map(
       i => i(22),
       q => q(22)
  );
  buf_x2_i23 : buf_x2
  port map(
       i => i(23),
       q => q(23)
  );
  buf_x2_i24 : buf_x2
  port map(
       i => i(24),
       q => q(24)
  );
  buf_x2_i25 : buf_x2
  port map(
       i => i(25),
       q => q(25)
  );
  buf_x2_i26 : buf_x2
  port map(
       i => i(26),
       q => q(26)
  );
  buf_x2_i27 : buf_x2
  port map(
       i => i(27),
       q => q(27)
  );
  buf_x2_i28 : buf_x2
  port map(
       i => i(28),
       q => q(28)
  );
  buf_x2_i29 : buf_x2
  port map(
       i => i(29),
       q => q(29)
  );
  buf_x2_i30 : buf_x2
  port map(
       i => i(30),
       q => q(30)
  );
  buf_x2_i31 : buf_x2
  port map(
       i => i(31),
       q => q(31)
  );
end behavioural ;
