--
-- Generated by VHDL export
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_signed.all;
entity zero_1 is
  port(
      nq    : OUT std_logic
  );
end zero_1;



architecture behavioural of zero_1 is

component zero_x0
  port (
  nq	: OUT STD_LOGIC
);
end component;


begin
  zero_x0_i0 : zero_x0
  port map(
       nq => nq
  );
end behavioural ;
